In [77]:
#sentiment analysis using average word2vec with help of randomforestclassifier algorithm

In [76]:
import pandas as pd
import numpy as np
import re
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

In [2]:
df=pd.read_csv("C:\\Users\\user\\OneDrive\\Documents\\setiment_analysis.csv")

In [3]:
pf=pd.DataFrame(df)

In [4]:
pf

Year  Month  Day Time of Tweet  \
0    2018      8   18       morning   
1    2018      8   18          noon   
2    2017      8   18         night   
3    2022      6    8       morning   
4    2022      6    8          noon   
..    ...    ...  ...           ...   
494  2015     10   18         night   
495  2021      2   25       morning   
496  2022      5   30          noon   
497  2018      8   10         night   
498  2019      3   25       morning   

                                                  text sentiment     Platform  
0                   what a great day look like a dream  positive    Twitter    
1       I feel sorry, I miss you here in the sea beach  positive    Facebook   
2                                       Don't angry me  negative     Facebook  
3    We attend in the class just for listening teac...  negative    Facebook   
4                    Those who want to go, let them go  negative   Instagram   
..                                                 ...       ...          ...  
494  According to , a quarter of families under six...  negative     Twitter   
495      the plan to not spend money is not going well  negative   Instagram   
496    uploading all my bamboozle pictures of facebook   neutral    Facebook   
497   congratulations ! you guys finish a month ear...  positive     Twitter   
498   actually, I wish I was back in Tahoe.  I miss...  negative   Instagram   

[499 rows x 7 columns]

In [5]:
pf.drop('Year',axis=1,inplace=True)

In [6]:
pf.drop('Month',axis=1,inplace=True)

In [7]:
pf.drop('Time of Tweet',axis=1,inplace=True)

In [8]:
pf.drop('Platform',axis=1,inplace=True)

In [9]:
pf.drop('Day',axis=1,inplace=True)

In [10]:
pf

text sentiment
0                   what a great day look like a dream  positive
1       I feel sorry, I miss you here in the sea beach  positive
2                                       Don't angry me  negative
3    We attend in the class just for listening teac...  negative
4                    Those who want to go, let them go  negative
..                                                 ...       ...
494  According to , a quarter of families under six...  negative
495      the plan to not spend money is not going well  negative
496    uploading all my bamboozle pictures of facebook   neutral
497   congratulations ! you guys finish a month ear...  positive
498   actually, I wish I was back in Tahoe.  I miss...  negative

[499 rows x 2 columns]

In [11]:
stem=PorterStemmer()

In [12]:
paragraph=[]
for i in range(len(pf)):
    review=re.sub('[^a-zA-Z]',' ',pf['text'][i])
    review=review.lower()
    review=review.split()
    review=[stem.stem(word) for word in review if word not in stopwords.words("english")]
    review=' '.join(review)
    paragraph.append(review)

In [13]:
paragraph

['great day look like dream',
 'feel sorri miss sea beach',
 'angri',
 'attend class listen teacher read slide nonsenc',
 'want go let go',
 'night feel neutral',
 'feed babi fun smile coo',
 'soooo high',
 '',
 'today first time arriv boat amaz journey',
 'love someth like e mc rule',
 'realli realli like song cardigan taylor swift',
 'sharpi run danger low ink',
 'want go music tonight lost voic',
 'alway somewher miss',
 'distrub',
 'care',
 'sick past day',
 'come back home past job realli good time',
 'never fall love found',
 'oh maya sorri hope find soon',
 'play kid amaz',
 'clean hous famili com later today',
 'tri shtdown pc accenditenli click restart button realli disgust',
 'follow follow',
 'amaz game play everyday',
 'sorri',
 'villag hardli found intern feel gloomi',
 'juss came back baris',
 'went sleep power cut villag',
 'look like compani new logo',
 'buy sophi world book realli happi',
 'consol got bmi test hahaha say obes well much unhappi minut',
 'funni cute kid'

In [14]:
count=0
for i in paragraph:
    if len(i)==0:
        count=count+1


In [15]:
count

3

In [16]:
from gensim.utils import simple_preprocess

In [17]:
sent=[]
for i in range(len(paragraph)):
    sent.append(simple_preprocess(paragraph[i]))

In [18]:
len(sent)

499

In [19]:
[[i,j,k] for i,j,k in zip(list(map(len,sent)),sent,pf['text']) if i<1]

[[0, [], ' Both of you'], [0, [], ' Both of you'], [0, [], ' There!']]

In [20]:
len(sent)

499

In [21]:
type(sent)

list

In [22]:
# applying map(function, iterable)
# lambda arguments : expression

In [23]:
x=pf[list(map(lambda x:len(x)>0,sent))]

In [24]:
x.columns

Index(['text', 'sentiment'], dtype='object')

In [25]:
y=x['sentiment']

In [26]:
y=y.reset_index()

In [27]:
y

index sentiment
0        0  positive
1        1  positive
2        2  negative
3        3  negative
4        4  negative
..     ...       ...
491    494  negative
492    495  negative
493    496   neutral
494    497  positive
495    498  negative

[496 rows x 2 columns]

In [28]:
x=x['text']

In [29]:
x

0                     what a great day look like a dream
1         I feel sorry, I miss you here in the sea beach
2                                         Don't angry me
3      We attend in the class just for listening teac...
4                      Those who want to go, let them go
                             ...                        
494    According to , a quarter of families under six...
495        the plan to not spend money is not going well
496      uploading all my bamboozle pictures of facebook
497     congratulations ! you guys finish a month ear...
498     actually, I wish I was back in Tahoe.  I miss...
Name: text, Length: 496, dtype: object

In [30]:
x.shape

(496,)

In [31]:
x=x.reset_index().copy()

In [32]:
x

index                                               text
0        0                 what a great day look like a dream
1        1     I feel sorry, I miss you here in the sea beach
2        2                                     Don't angry me
3        3  We attend in the class just for listening teac...
4        4                  Those who want to go, let them go
..     ...                                                ...
491    494  According to , a quarter of families under six...
492    495      the plan to not spend money is not going well
493    496    uploading all my bamboozle pictures of facebook
494    497   congratulations ! you guys finish a month ear...
495    498   actually, I wish I was back in Tahoe.  I miss...

[496 rows x 2 columns]

In [33]:
sent=[]
for i in range(len(x)):
    sent.append(simple_preprocess(x['text'][i]))
    

In [34]:
sent

[['what', 'great', 'day', 'look', 'like', 'dream'],
 ['feel', 'sorry', 'miss', 'you', 'here', 'in', 'the', 'sea', 'beach'],
 ['don', 'angry', 'me'],
 ['we',
  'attend',
  'in',
  'the',
  'class',
  'just',
  'for',
  'listening',
  'teachers',
  'reading',
  'on',
  'slide',
  'just',
  'nonsence'],
 ['those', 'who', 'want', 'to', 'go', 'let', 'them', 'go'],
 ['its', 'night', 'am', 'feeling', 'neutral'],
 ['am',
  'feedings',
  'for',
  'the',
  'baby',
  'are',
  'fun',
  'when',
  'he',
  'is',
  'all',
  'smiles',
  'and',
  'coos'],
 ['soooo', 'high'],
 ['today',
  'first',
  'time',
  'arrive',
  'in',
  'the',
  'boat',
  'its',
  'amazing',
  'journey'],
 ['love', 'is', 'something', 'like', 'mc', 'rules'],
 ['really',
  'really',
  'like',
  'the',
  'song',
  'cardigan',
  'by',
  'taylor',
  'swift'],
 ['my', 'sharpie', 'is', 'running', 'dangerously', 'low', 'on', 'ink'],
 ['want', 'to', 'go', 'to', 'music', 'tonight', 'but', 'lost', 'my', 'voice'],
 ['always', 'somewhere', '

In [35]:
len(sent)

496

In [36]:
from gensim.models import Word2Vec

In [37]:
max_vocab=500

In [38]:
vector=Word2Vec(max_vocab_size=max_vocab,sentences=sent,vector_size=100,min_count=1)

In [39]:
vector.wv.most_similar(['finish'])

[('act', 0.34932103753089905),
 ('son', 0.3044849634170532),
 ('has', 0.2721931040287018),
 ('we', 0.2683246433734894),
 ('world', 0.2614533305168152),
 ('rush', 0.2612273395061493),
 ('mum', 0.2589936852455139),
 ('make', 0.25704264640808105),
 ('ever', 0.2524738013744354),
 ('too', 0.24710749089717865)]

In [40]:
vector.wv['finish']

array([-8.89231078e-03, -4.94950125e-03,  1.54195889e-03,  2.24844087e-03,
        2.38190667e-04, -6.82683056e-03, -6.68212259e-03, -1.73521065e-03,
       -6.89130323e-03, -6.56089419e-03, -2.05857155e-04, -4.06174688e-03,
       -3.28078307e-03,  8.57497333e-04,  1.92691118e-03,  6.36633777e-04,
        1.89899467e-03,  4.64447914e-03, -6.67963224e-03, -5.34413755e-03,
       -1.08704937e-03,  5.04782936e-03,  2.32616859e-03, -9.03909840e-03,
       -7.32226437e-03,  9.11937188e-03,  2.69014086e-03,  8.32982920e-03,
       -1.05937300e-02, -8.25368520e-03,  1.17801121e-02,  4.28605033e-03,
       -4.47907904e-03,  3.78617854e-03,  7.59128062e-03, -5.53500885e-03,
        4.15264349e-03, -3.22964299e-03, -6.33653067e-03,  4.96094627e-03,
        5.97914029e-03, -8.18753557e-04,  5.47055202e-03,  2.97879032e-03,
        1.07220151e-02,  6.06758753e-03,  7.84422364e-03, -7.31694419e-03,
        8.02609324e-03, -7.38030439e-03,  6.15766132e-03,  6.50684768e-03,
       -1.63103186e-03,  

In [41]:
vector.wv.index_to_key

['to',
 'the',
 'you',
 'and',
 'my',
 'it',
 'for',
 'is',
 'in',
 'that',
 'me',
 'day',
 'are',
 'have',
 'of',
 'but',
 'on',
 'was',
 'now',
 'just',
 'love',
 'so',
 'be',
 'not',
 'with',
 'know',
 'going',
 'what',
 'like',
 'up',
 'go',
 'we',
 'this',
 'happy',
 'all',
 'today',
 'really',
 'out',
 'do',
 'at',
 'back',
 'don',
 'am',
 'its',
 'got',
 'good',
 'im',
 'can',
 'too',
 'there',
 'want',
 'tomorrow',
 'will',
 'new',
 'from',
 'home',
 'amazing',
 'miss',
 'if',
 'morning',
 'time',
 'some',
 'sorry',
 'about',
 'no',
 'need',
 'her',
 'then',
 'night',
 'only',
 'your',
 'when',
 'much',
 'big',
 'feel',
 'days',
 'he',
 'get',
 'thanks',
 'our',
 'well',
 'work',
 'here',
 'hope',
 'went',
 'through',
 'still',
 'fun',
 'great',
 'getting',
 'tonight',
 'always',
 'an',
 'mom',
 'feeling',
 'off',
 'haha',
 'world',
 'how',
 'him',
 've',
 'see',
 'let',
 'one',
 'because',
 'which',
 'who',
 'thinking',
 'last',
 'been',
 'best',
 'looks',
 'soon',
 'coffee',


In [42]:
vector.wv.key_to_index

{'to': 0,
 'the': 1,
 'you': 2,
 'and': 3,
 'my': 4,
 'it': 5,
 'for': 6,
 'is': 7,
 'in': 8,
 'that': 9,
 'me': 10,
 'day': 11,
 'are': 12,
 'have': 13,
 'of': 14,
 'but': 15,
 'on': 16,
 'was': 17,
 'now': 18,
 'just': 19,
 'love': 20,
 'so': 21,
 'be': 22,
 'not': 23,
 'with': 24,
 'know': 25,
 'going': 26,
 'what': 27,
 'like': 28,
 'up': 29,
 'go': 30,
 'we': 31,
 'this': 32,
 'happy': 33,
 'all': 34,
 'today': 35,
 'really': 36,
 'out': 37,
 'do': 38,
 'at': 39,
 'back': 40,
 'don': 41,
 'am': 42,
 'its': 43,
 'got': 44,
 'good': 45,
 'im': 46,
 'can': 47,
 'too': 48,
 'there': 49,
 'want': 50,
 'tomorrow': 51,
 'will': 52,
 'new': 53,
 'from': 54,
 'home': 55,
 'amazing': 56,
 'miss': 57,
 'if': 58,
 'morning': 59,
 'time': 60,
 'some': 61,
 'sorry': 62,
 'about': 63,
 'no': 64,
 'need': 65,
 'her': 66,
 'then': 67,
 'night': 68,
 'only': 69,
 'your': 70,
 'when': 71,
 'much': 72,
 'big': 73,
 'feel': 74,
 'days': 75,
 'he': 76,
 'get': 77,
 'thanks': 78,
 'our': 79,
 'well': 80

In [43]:
import numpy as np

In [44]:
def avgword2vec(doc):
    return np.mean([vector.wv[word] for word in doc if word in vector.wv.index_to_key],axis=0)

In [45]:
from tqdm import tqdm

In [46]:
x=[]
for i in tqdm(range(len(sent))):
    x.append(avgword2vec(sent[i]))

  0%|          | 0/496 [00:00<?, ?it/s]C:\Users\user\AppData\Roaming\Python\Python312\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\Users\user\AppData\Roaming\Python\Python312\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
100%|██████████| 496/496 [00:00<00:00, 14272.31it/s]


In [47]:
len(x)

496

In [48]:
x[0].shape

(100,)

In [49]:
y

index sentiment
0        0  positive
1        1  positive
2        2  negative
3        3  negative
4        4  negative
..     ...       ...
491    494  negative
492    495  negative
493    496   neutral
494    497  positive
495    498  negative

[496 rows x 2 columns]

In [50]:
value={"positive":2,"neutral":1,"negative":0}

In [51]:
y['sentiment']=y['sentiment'].map(value)

In [52]:
y

index  sentiment
0        0          2
1        1          2
2        2          0
3        3          0
4        4          0
..     ...        ...
491    494          0
492    495          0
493    496          1
494    497          2
495    498          0

[496 rows x 2 columns]

In [53]:
y.drop('index',axis=1,inplace=True)

In [54]:
y

sentiment
0            2
1            2
2            0
3            0
4            0
..         ...
491          0
492          0
493          1
494          2
495          0

[496 rows x 1 columns]

In [55]:
len(x)

496

In [56]:
y['sentiment'].unique()

array([2, 0, 1], dtype=int64)

In [57]:
pf['sentiment'].isnull().sum()

0

In [58]:
x[0].reshape(1,-1)

array([[-0.00238304,  0.01106968,  0.00079306, -0.00087237,  0.00639242,
        -0.02119862,  0.01217468,  0.02027438, -0.00997964, -0.0075199 ,
        -0.00625216, -0.01860007, -0.00029765,  0.00667921, -0.00390674,
        -0.00845826,  0.00375215, -0.01214676, -0.00282325, -0.02260419,
         0.00715516, -0.00266446,  0.00799545, -0.00944795, -0.00550951,
        -0.00400926, -0.00941228, -0.00339629, -0.00993458,  0.00014444,
         0.01590314, -0.0025111 ,  0.00894519, -0.0187486 , -0.01040902,
         0.01152739, -0.00049262, -0.00386056, -0.0054    , -0.01967498,
        -0.00230383, -0.00541273, -0.00570113, -0.00958275,  0.01119675,
         0.00055777, -0.00963309,  0.00085683,  0.0032056 ,  0.00813946,
         0.00238976, -0.01781281,  0.00597981,  0.00184015,  0.00038893,
         0.00108837,  0.00457888, -0.00058103, -0.014456  ,  0.00794473,
        -0.00027069, -0.00557712,  0.00273733, -0.00539275, -0.01774139,
         0.00773313,  0.00349553,  0.01471172, -0.0

In [59]:
input_df=pd.DataFrame()
for i in range(len(x)):
    input_df[i]=pd.DataFrame(x[i].reshape(-1,1))

C:\Users\user\AppData\Local\Temp\ipykernel_34048\1380088790.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  input_df[i]=pd.DataFrame(x[i].reshape(-1,1))
C:\Users\user\AppData\Local\Temp\ipykernel_34048\1380088790.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  input_df[i]=pd.DataFrame(x[i].reshape(-1,1))
C:\Users\user\AppData\Local\Temp\ipykernel_34048\1380088790.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Conside

In [60]:
input_df=input_df.T

In [61]:
input_df

0         1         2         3         4         5         6   \
0   -0.002383  0.011070  0.000793 -0.000872  0.006392 -0.021199  0.012175   
1   -0.008798  0.010170  0.004788 -0.001547  0.011341 -0.024399  0.014757   
2   -0.006772  0.012152  0.005644 -0.010615  0.004852 -0.027949  0.009656   
3   -0.007367  0.010320  0.007022  0.001331  0.006720 -0.026856  0.018224   
4   -0.007549  0.008722  0.004765  0.002544  0.001182 -0.027711  0.017796   
..        ...       ...       ...       ...       ...       ...       ...   
491 -0.005381  0.007058  0.001312 -0.001948  0.005120 -0.018733  0.012298   
492 -0.009127  0.009892  0.003271  0.000055  0.002742 -0.024150  0.012081   
493 -0.002658  0.007701  0.002691 -0.000305  0.002799 -0.013621  0.008772   
494 -0.004901  0.001959  0.002474  0.000241  0.001253 -0.008414  0.003741   
495 -0.010323  0.008885  0.003663 -0.003856  0.002989 -0.021578  0.012888   

           7         8         9   ...        90        91        92  \
0    0.020274 -0.009980 -0.007520  ...  0.017169  0.013859 -0.000232   
1    0.023417 -0.014342 -0.009449  ...  0.014427  0.013615  0.003088   
2    0.023429 -0.011994 -0.014099  ...  0.025337  0.013253  0.004495   
3    0.024098 -0.013289 -0.011243  ...  0.022654  0.015577  0.001791   
4    0.021943 -0.014213 -0.007646  ...  0.018057  0.012164  0.008130   
..        ...       ...       ...  ...       ...       ...       ...   
491  0.015115 -0.008824 -0.004978  ...  0.011786  0.007467  0.000990   
492  0.025272 -0.014776 -0.010043  ...  0.022062  0.009984  0.000512   
493  0.020481 -0.005801 -0.007487  ...  0.011545  0.004803  0.004232   
494  0.009420 -0.004279 -0.004298  ...  0.009316  0.006169  0.001392   
495  0.017950 -0.009327 -0.007947  ...  0.017786  0.010788  0.001341   

           93        94        95        96        97        98        99  
0    0.000844  0.015567  0.005452  0.000690 -0.006245  0.004921 -0.000489  
1    0.001742  0.019612  0.011036  0.009822 -0.001158  0.007448 -0.001973  
2    0.004006  0.007615  0.007531  0.010646 -0.010424  0.010995 -0.008703  
3    0.003552  0.016267  0.006885  0.005914 -0.000791  0.005867  0.002239  
4    0.004435  0.019422  0.009856  0.002922 -0.003272  0.005917  0.000407  
..        ...       ...       ...       ...       ...       ...       ...  
491 -0.001286  0.011677  0.006381  0.005123 -0.002596  0.004105  0.001290  
492  0.000826  0.016169  0.008811  0.007650 -0.005896  0.006964  0.000131  
493  0.000275  0.009744  0.002044  0.000654 -0.001946  0.004251  0.000376  
494 -0.000387  0.006931  0.002921  0.003351 -0.003092  0.002245  0.000074  
495 -0.003101  0.014904  0.009348  0.005237 -0.001664  0.005251 -0.005614  

[496 rows x 100 columns]

In [62]:
input_df['y']=y['sentiment']

In [63]:
input_df

0         1         2         3         4         5         6  \
0   -0.002383  0.011070  0.000793 -0.000872  0.006392 -0.021199  0.012175   
1   -0.008798  0.010170  0.004788 -0.001547  0.011341 -0.024399  0.014757   
2   -0.006772  0.012152  0.005644 -0.010615  0.004852 -0.027949  0.009656   
3   -0.007367  0.010320  0.007022  0.001331  0.006720 -0.026856  0.018224   
4   -0.007549  0.008722  0.004765  0.002544  0.001182 -0.027711  0.017796   
..        ...       ...       ...       ...       ...       ...       ...   
491 -0.005381  0.007058  0.001312 -0.001948  0.005120 -0.018733  0.012298   
492 -0.009127  0.009892  0.003271  0.000055  0.002742 -0.024150  0.012081   
493 -0.002658  0.007701  0.002691 -0.000305  0.002799 -0.013621  0.008772   
494 -0.004901  0.001959  0.002474  0.000241  0.001253 -0.008414  0.003741   
495 -0.010323  0.008885  0.003663 -0.003856  0.002989 -0.021578  0.012888   

            7         8         9  ...        91        92        93  \
0    0.020274 -0.009980 -0.007520  ...  0.013859 -0.000232  0.000844   
1    0.023417 -0.014342 -0.009449  ...  0.013615  0.003088  0.001742   
2    0.023429 -0.011994 -0.014099  ...  0.013253  0.004495  0.004006   
3    0.024098 -0.013289 -0.011243  ...  0.015577  0.001791  0.003552   
4    0.021943 -0.014213 -0.007646  ...  0.012164  0.008130  0.004435   
..        ...       ...       ...  ...       ...       ...       ...   
491  0.015115 -0.008824 -0.004978  ...  0.007467  0.000990 -0.001286   
492  0.025272 -0.014776 -0.010043  ...  0.009984  0.000512  0.000826   
493  0.020481 -0.005801 -0.007487  ...  0.004803  0.004232  0.000275   
494  0.009420 -0.004279 -0.004298  ...  0.006169  0.001392 -0.000387   
495  0.017950 -0.009327 -0.007947  ...  0.010788  0.001341 -0.003101   

           94        95        96        97        98        99  y  
0    0.015567  0.005452  0.000690 -0.006245  0.004921 -0.000489  2  
1    0.019612  0.011036  0.009822 -0.001158  0.007448 -0.001973  2  
2    0.007615  0.007531  0.010646 -0.010424  0.010995 -0.008703  0  
3    0.016267  0.006885  0.005914 -0.000791  0.005867  0.002239  0  
4    0.019422  0.009856  0.002922 -0.003272  0.005917  0.000407  0  
..        ...       ...       ...       ...       ...       ... ..  
491  0.011677  0.006381  0.005123 -0.002596  0.004105  0.001290  0  
492  0.016169  0.008811  0.007650 -0.005896  0.006964  0.000131  0  
493  0.009744  0.002044  0.000654 -0.001946  0.004251  0.000376  1  
494  0.006931  0.002921  0.003351 -0.003092  0.002245  0.000074  2  
495  0.014904  0.009348  0.005237 -0.001664  0.005251 -0.005614  0  

[496 rows x 101 columns]

In [64]:
input_df=input_df.dropna()

In [65]:
input_df.shape

(484, 101)

In [66]:
y=input_df['y']

In [67]:
x=input_df.iloc[:,0:100]

In [68]:
x

0         1         2         3         4         5         6   \
0   -0.002383  0.011070  0.000793 -0.000872  0.006392 -0.021199  0.012175   
1   -0.008798  0.010170  0.004788 -0.001547  0.011341 -0.024399  0.014757   
2   -0.006772  0.012152  0.005644 -0.010615  0.004852 -0.027949  0.009656   
3   -0.007367  0.010320  0.007022  0.001331  0.006720 -0.026856  0.018224   
4   -0.007549  0.008722  0.004765  0.002544  0.001182 -0.027711  0.017796   
..        ...       ...       ...       ...       ...       ...       ...   
491 -0.005381  0.007058  0.001312 -0.001948  0.005120 -0.018733  0.012298   
492 -0.009127  0.009892  0.003271  0.000055  0.002742 -0.024150  0.012081   
493 -0.002658  0.007701  0.002691 -0.000305  0.002799 -0.013621  0.008772   
494 -0.004901  0.001959  0.002474  0.000241  0.001253 -0.008414  0.003741   
495 -0.010323  0.008885  0.003663 -0.003856  0.002989 -0.021578  0.012888   

           7         8         9   ...        90        91        92  \
0    0.020274 -0.009980 -0.007520  ...  0.017169  0.013859 -0.000232   
1    0.023417 -0.014342 -0.009449  ...  0.014427  0.013615  0.003088   
2    0.023429 -0.011994 -0.014099  ...  0.025337  0.013253  0.004495   
3    0.024098 -0.013289 -0.011243  ...  0.022654  0.015577  0.001791   
4    0.021943 -0.014213 -0.007646  ...  0.018057  0.012164  0.008130   
..        ...       ...       ...  ...       ...       ...       ...   
491  0.015115 -0.008824 -0.004978  ...  0.011786  0.007467  0.000990   
492  0.025272 -0.014776 -0.010043  ...  0.022062  0.009984  0.000512   
493  0.020481 -0.005801 -0.007487  ...  0.011545  0.004803  0.004232   
494  0.009420 -0.004279 -0.004298  ...  0.009316  0.006169  0.001392   
495  0.017950 -0.009327 -0.007947  ...  0.017786  0.010788  0.001341   

           93        94        95        96        97        98        99  
0    0.000844  0.015567  0.005452  0.000690 -0.006245  0.004921 -0.000489  
1    0.001742  0.019612  0.011036  0.009822 -0.001158  0.007448 -0.001973  
2    0.004006  0.007615  0.007531  0.010646 -0.010424  0.010995 -0.008703  
3    0.003552  0.016267  0.006885  0.005914 -0.000791  0.005867  0.002239  
4    0.004435  0.019422  0.009856  0.002922 -0.003272  0.005917  0.000407  
..        ...       ...       ...       ...       ...       ...       ...  
491 -0.001286  0.011677  0.006381  0.005123 -0.002596  0.004105  0.001290  
492  0.000826  0.016169  0.008811  0.007650 -0.005896  0.006964  0.000131  
493  0.000275  0.009744  0.002044  0.000654 -0.001946  0.004251  0.000376  
494 -0.000387  0.006931  0.002921  0.003351 -0.003092  0.002245  0.000074  
495 -0.003101  0.014904  0.009348  0.005237 -0.001664  0.005251 -0.005614  

[484 rows x 100 columns]

In [69]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [70]:
rfc=RandomForestClassifier()

In [71]:
rfc.fit(x,y)

RandomForestClassifier()

In [72]:
pred=rfc.predict(x)

In [73]:
print(accuracy_score(y,pred))

0.993801652892562


In [74]:
print(confusion_matrix(y,pred))

[[130   1   1]
 [  0 187   1]
 [  0   0 164]]


In [75]:
print(classification_report(y,pred))

              precision    recall  f1-score   support

           0       1.00      0.98      0.99       132
           1       0.99      0.99      0.99       188
           2       0.99      1.00      0.99       164

    accuracy                           0.99       484
   macro avg       0.99      0.99      0.99       484
weighted avg       0.99      0.99      0.99       484

