In [345]:
from sklearn.feature_extraction.text import CountVectorizer

In [346]:
sentence="""
 hello how are you,
 hello what about you,
 hello what do want,
 i am good,
 i am fine,
 i am bad
"""

In [347]:
for sent in sentence.split(','):
    print([sent])

['\n hello how are you']
['\n hello what about you']
['\n hello what do want']
['\n i am good']
['\n i am fine']
['\n i am bad\n']


In [348]:
data=({"wealth":[ "hello how are you",
"hello what about you",
"hello what do want",
"i am good",
"i am fine",
"i am bad"],
"label":[0,0,0,1,1,1]})

In [349]:
data

{'wealth': ['hello how are you',
  'hello what about you',
  'hello what do want',
  'i am good',
  'i am fine',
  'i am bad'],
 'label': [0, 0, 0, 1, 1, 1]}

In [350]:
import pandas as pd

In [351]:
data=pd.DataFrame(data)

In [352]:
data.sample(3)

wealth  label
1  hello what about you      0
5              i am bad      1
2    hello what do want      0

In [353]:
count=CountVectorizer(stop_words='english',ngram_range=(1,2))

In [354]:
num=count.fit_transform(data["wealth"])

In [355]:
num.toarray()

array([[0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0]], dtype=int64)

In [356]:
count.vocabulary_

{'hello': 3, 'want': 5, 'hello want': 4, 'good': 2, 'fine': 1, 'bad': 0}

In [357]:
data["wealth"]

0       hello how are you
1    hello what about you
2      hello what do want
3               i am good
4               i am fine
5                i am bad
Name: wealth, dtype: object

In [358]:
#hello=>3,want=>1,good=>1,fine=>1,bad=>1

In [359]:
count.vocabulary_

{'hello': 3, 'want': 5, 'hello want': 4, 'good': 2, 'fine': 1, 'bad': 0}

In [416]:
# using some daaset set to predict

In [360]:
import numpy as np

In [361]:
dataset=pd.read_csv("C:\\Users\\user\\OneDrive\\Documents\\spamham.csv")

In [362]:
pf=pd.DataFrame(dataset)
print(pf.columns)

Index(['Text', 'Class', 'Label'], dtype='object')


In [363]:
print(pf)

                                                   Text  Class Label
0     Supply Quality China's EXCLUSIVE dimensions at...      1  spam
1                            over. SidLet me know. Thx.      0   ham
2     Dear Friend,Greetings to you.I wish to accost ...      1  spam
3     MR. CHEUNG PUIHANG SENG BANK LTD.DES VOEUX RD....      1  spam
4             Not a surprising assessment from Embassy.      0   ham
...                                                 ...    ...   ...
4840  It has been prepared- ready for your signature...      0   ham
4841                                     And to you too      0   ham
4842   <html><head><style>P{margin:0px;padding:0px}body      1  spam
4843  Robinson talking now voice cracking but resolu...      0   ham
4844  PIR <preines(Wednesday February 10 2010 1:16 P...      0   ham

[4845 rows x 3 columns]


In [364]:
#here 1==>spam==>fake news
#here 0==>ham==>real news

In [365]:
pf.drop("Label",axis=1,inplace=True)

In [366]:
pf

Text  Class
0     Supply Quality China's EXCLUSIVE dimensions at...      1
1                            over. SidLet me know. Thx.      0
2     Dear Friend,Greetings to you.I wish to accost ...      1
3     MR. CHEUNG PUIHANG SENG BANK LTD.DES VOEUX RD....      1
4             Not a surprising assessment from Embassy.      0
...                                                 ...    ...
4840  It has been prepared- ready for your signature...      0
4841                                     And to you too      0
4842   <html><head><style>P{margin:0px;padding:0px}body      1
4843  Robinson talking now voice cracking but resolu...      0
4844  PIR <preines(Wednesday February 10 2010 1:16 P...      0

[4845 rows x 2 columns]

In [367]:
len(pf)

4845

In [368]:
pf.isnull().sum()

Text     0
Class    0
dtype: int64

In [369]:
pf['Class'].unique()

array([1, 0], dtype=int64)

In [370]:
pf["Class"].value_counts()

Class
0    2732
1    2113
Name: count, dtype: int64

In [371]:
import nltk
from nltk.corpus import stopwords

In [372]:
from nltk.stem import PorterStemmer

In [373]:
stem=PorterStemmer()

In [374]:
import re

In [375]:
pf["Text"]

0       Supply Quality China's EXCLUSIVE dimensions at...
1                              over. SidLet me know. Thx.
2       Dear Friend,Greetings to you.I wish to accost ...
3       MR. CHEUNG PUIHANG SENG BANK LTD.DES VOEUX RD....
4               Not a surprising assessment from Embassy.
                              ...                        
4840    It has been prepared- ready for your signature...
4841                                       And to you too
4842     <html><head><style>P{margin:0px;padding:0px}body
4843    Robinson talking now voice cracking but resolu...
4844    PIR <preines(Wednesday February 10 2010 1:16 P...
Name: Text, Length: 4845, dtype: object

In [376]:
def remove_unwant(content):
    text=re.sub('[^a-zA-Z]',' ',content)
    text=text.lower()
    text=text.split()
    text=[stem.stem(word) for word in text if word not in stopwords.words("english")]
    review=' '.join(text)
    return review
        

In [377]:
pf["Text"]=pf["Text"].apply(remove_unwant)

In [378]:
pf["Text"]

0       suppli qualiti china exclus dimens unbeat pric...
1                                         sidlet know thx
2       dear friend greet wish accost request would im...
3       mr cheung puihang seng bank ltd de voeux rd br...
4                                  surpris assess embassi
                              ...                        
4840                       prepar readi signatur tomorrow
4841                                                     
4842              html head style p margin px pad px bodi
4843    robinson talk voic crack resolut carv stay fir...
4844    pir prein wednesday februari pmcdm huma abedin...
Name: Text, Length: 4845, dtype: object

In [379]:
corpus=[]
for i in range(0,len(pf)):
    text=re.sub('[^a-zA-Z]',' ',pf["Text"][i])
    text=text.lower()
    text=text.split()
    text=[stem.stem(word) for word in text if word not in stopwords.words("english")]
    review=' '.join(text)
    corpus.append(review)

In [380]:
corpus

['suppli qualiti china exclu dimen unbeat price dear sir plea inform one china largest export import sto ne compani wanliston group group subsidiari special q uarri process sale dimen stone slab tile dimen sion stone product build materi sector specialti market e group oper base xiamen south china lar gest export import busi portal china wanliston oper variou natur stone deposit squar meter th e countri addit quarri wanliston fulli autom pro cess plant process granit marbl granit prod uct wanliston suppli granit raw block form granit marbl tile strip vari dimen memori materi specialti product local specif export market group full rang china natur stone product includ pink color g g g g yellow color g dark g black g',
 'sidlet know thx',
 'dear friend greet wish accost request would immen benefit us executor possibl may tempt make fortun client situat cannot help left better option issu present case client fortun next kin unfortun next kin die day st octob egyptian airlin passeng board 

In [381]:
from sklearn.feature_extraction.text import CountVectorizer

In [382]:
x=pf["Text"]


In [383]:
pf.columns

Index(['Text', 'Class'], dtype='object')

In [384]:
y=pf["Class"]

In [385]:
from sklearn.model_selection import train_test_split

In [386]:
vector=CountVectorizer()
x=vector.fit_transform(x)

In [387]:
x=x.toarray()

In [388]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=4,stratify=y)

In [389]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((3633, 61425), (1212, 61425), (3633,), (1212,))

In [390]:
from sklearn.linear_model import LogisticRegression

In [391]:
linear=LogisticRegression()
linear.fit(x_train,y_train)

LogisticRegression()

In [392]:
pred=linear.predict(x_train)


In [393]:
pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [394]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [395]:
print(accuracy_score(pred,y_train))

0.9977979631158822


In [396]:
prediction=linear.predict(x_test)

In [397]:
print(accuracy_score(prediction,y_test))

0.981023102310231


In [398]:
confusion_matrix(prediction,y_test)

array([[679,  19],
       [  4, 510]], dtype=int64)

In [ ]:
#[true,positive][false positive]
#[false,negative][false positive]

In [399]:
confusion_matrix(pred,y_train)

array([[2049,    8],
       [   0, 1576]], dtype=int64)

In [410]:
text=x_test[0]

preds=linear.predict([text])
print(preds)
if(preds==1):
    print("it is spam and it is fake")
else:
    print("it is ham and it is real news")

[1]
it is spam and it is fake


In [411]:
prediction

array([1, 1, 0, ..., 0, 0, 0], dtype=int64)

In [412]:
vector.vocabulary_

{'suppli': 47629,
 'qualiti': 41805,
 'china': 9160,
 'exclus': 16277,
 'dimens': 12739,
 'unbeat': 52652,
 'price': 40579,
 'dear': 11841,
 'sir': 46075,
 'pleas': 39874,
 'inform': 24368,
 'one': 37765,
 'largest': 29331,
 'export': 16397,
 'import': 24059,
 'sto': 47208,
 'ne': 35221,
 'compani': 10225,
 'wanliston': 55925,
 'group': 20215,
 'subsidiari': 47426,
 'special': 46683,
 'uarri': 51958,
 'process': 40699,
 'sale': 44614,
 'stone': 47223,
 'slab': 46166,
 'tile': 50401,
 'dimen': 12738,
 'sion': 46072,
 'product': 40719,
 'build': 7581,
 'materi': 32098,
 'sector': 45151,
 'specialti': 46696,
 'market': 32011,
 'oper': 37951,
 'base': 5509,
 'xiamen': 57923,
 'south': 46615,
 'lar': 29319,
 'gest': 19451,
 'busi': 7656,
 'portal': 40187,
 'own': 38621,
 'variou': 53898,
 'natur': 34387,
 'deposit': 12180,
 'squar': 46840,
 'meter': 32621,
 'th': 49111,
 'countri': 10930,
 'addit': 753,
 'quarri': 41816,
 'fulli': 18572,
 'autom': 4580,
 'pro': 40671,
 'cess': 8789,
 'plant

In [ ]:
#advantages:
#=>it is simple for implementation

#Disadvantages
#=>sparse matrix
#=>out of vocabulary
#=>semantic information cannot be captured
#=>cannot 
# fixed size array


In [414]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)