In [100]:
from sklearn.feature_extraction.text import CountVectorizer

In [101]:
sentence="""
 hello how are you,
 hello what about you,
 hello what do want,
 i am good,
 i am fine,
 i am bad
"""

In [102]:
for sent in sentence.split(','):
    print([sent])

['\n hello how are you']
['\n hello what about you']
['\n hello what do want']
['\n i am good']
['\n i am fine']
['\n i am bad\n']


In [103]:
data=({"wealth":[ "hello how are you",
"hello what about you",
"hello what do want",
"i am good",
"i am fine",
"i am bad"],
"label":[0,0,0,1,1,1]})

In [104]:
data

{'wealth': ['hello how are you',
  'hello what about you',
  'hello what do want',
  'i am good',
  'i am fine',
  'i am bad'],
 'label': [0, 0, 0, 1, 1, 1]}

In [105]:
import pandas as pd

In [106]:
data=pd.DataFrame(data)
data

wealth  label
0     hello how are you      0
1  hello what about you      0
2    hello what do want      0
3             i am good      1
4             i am fine      1
5              i am bad      1

In [107]:
data.sample(3)

wealth  label
3           i am good      1
5            i am bad      1
2  hello what do want      0

In [108]:
count=CountVectorizer(stop_words='english',ngram_range=(1,2))

In [109]:
num=count.fit_transform(data["wealth"])

In [110]:
num.toarray()

array([[0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0]], dtype=int64)

In [111]:
count.vocabulary_

{'hello': 3, 'want': 5, 'hello want': 4, 'good': 2, 'fine': 1, 'bad': 0}

In [112]:
data["wealth"]

0       hello how are you
1    hello what about you
2      hello what do want
3               i am good
4               i am fine
5                i am bad
Name: wealth, dtype: object

In [113]:
#hello=>3,want=>1,good=>1,fine=>1,bad=>1

In [114]:
count.vocabulary_

{'hello': 3, 'want': 5, 'hello want': 4, 'good': 2, 'fine': 1, 'bad': 0}

In [115]:
# using some daaset set to predict

In [116]:
import numpy as np

In [117]:
dataset=pd.read_csv("C:\\Users\\user\\OneDrive\\Documents\\spamham.csv")

In [118]:
pf=pd.DataFrame(dataset)
print(pf.columns)

Index(['Text', 'Class', 'Label'], dtype='object')


In [119]:
print(pf)

                                                   Text  Class Label
0     Supply Quality China's EXCLUSIVE dimensions at...      1  spam
1                            over. SidLet me know. Thx.      0   ham
2     Dear Friend,Greetings to you.I wish to accost ...      1  spam
3     MR. CHEUNG PUIHANG SENG BANK LTD.DES VOEUX RD....      1  spam
4             Not a surprising assessment from Embassy.      0   ham
...                                                 ...    ...   ...
4840  It has been prepared- ready for your signature...      0   ham
4841                                     And to you too      0   ham
4842   <html><head><style>P{margin:0px;padding:0px}body      1  spam
4843  Robinson talking now voice cracking but resolu...      0   ham
4844  PIR <preines(Wednesday February 10 2010 1:16 P...      0   ham

[4845 rows x 3 columns]


In [120]:
#here 1==>spam==>fake news
#here 0==>ham==>real news

In [121]:
pf.drop("Label",axis=1,inplace=True)

In [122]:
pf

Text  Class
0     Supply Quality China's EXCLUSIVE dimensions at...      1
1                            over. SidLet me know. Thx.      0
2     Dear Friend,Greetings to you.I wish to accost ...      1
3     MR. CHEUNG PUIHANG SENG BANK LTD.DES VOEUX RD....      1
4             Not a surprising assessment from Embassy.      0
...                                                 ...    ...
4840  It has been prepared- ready for your signature...      0
4841                                     And to you too      0
4842   <html><head><style>P{margin:0px;padding:0px}body      1
4843  Robinson talking now voice cracking but resolu...      0
4844  PIR <preines(Wednesday February 10 2010 1:16 P...      0

[4845 rows x 2 columns]

In [123]:
len(pf)

4845

In [124]:
pf.isnull().sum()

Text     0
Class    0
dtype: int64

In [125]:
pf['Class'].unique()

array([1, 0], dtype=int64)

In [126]:
pf["Class"].value_counts()

Class
0    2732
1    2113
Name: count, dtype: int64

In [127]:
import nltk
from nltk.corpus import stopwords

In [128]:
from nltk.stem import PorterStemmer

In [129]:
stem=PorterStemmer()

In [130]:
import re

In [131]:
pf["Text"]

0       Supply Quality China's EXCLUSIVE dimensions at...
1                              over. SidLet me know. Thx.
2       Dear Friend,Greetings to you.I wish to accost ...
3       MR. CHEUNG PUIHANG SENG BANK LTD.DES VOEUX RD....
4               Not a surprising assessment from Embassy.
                              ...                        
4840    It has been prepared- ready for your signature...
4841                                       And to you too
4842     <html><head><style>P{margin:0px;padding:0px}body
4843    Robinson talking now voice cracking but resolu...
4844    PIR <preines(Wednesday February 10 2010 1:16 P...
Name: Text, Length: 4845, dtype: object

In [132]:
def remove_unwant(content):
    text=re.sub('[^a-zA-Z]',' ',content)
    text=text.lower()
    text=text.split()
    text=[stem.stem(word) for word in text if word not in stopwords.words("english")]
    review=' '.join(text)
    return review
        

In [133]:
pf["Text"]=pf["Text"].apply(remove_unwant)

In [134]:
pf["Text"]

0       suppli qualiti china exclus dimens unbeat pric...
1                                         sidlet know thx
2       dear friend greet wish accost request would im...
3       mr cheung puihang seng bank ltd de voeux rd br...
4                                  surpris assess embassi
                              ...                        
4840                       prepar readi signatur tomorrow
4841                                                     
4842              html head style p margin px pad px bodi
4843    robinson talk voic crack resolut carv stay fir...
4844    pir prein wednesday februari pmcdm huma abedin...
Name: Text, Length: 4845, dtype: object

In [135]:
#you can use this method also

In [136]:
#corpus=[]
#for i in range(0,len(pf)):
#    text=re.sub('[^a-zA-Z]',' ',pf["Text"][i])
#    text=text.lower()
#    text=text.split()
#    text=[stem.stem(word) for word in text if word not in stopwords.words("english")]
#    review=' '.join(text)
#    corpus.append(review)

In [137]:
from sklearn.feature_extraction.text import CountVectorizer

In [138]:
x=pf["Text"]


In [139]:
pf.columns

Index(['Text', 'Class'], dtype='object')

In [140]:
y=pf["Class"]

In [141]:
from sklearn.model_selection import train_test_split

In [142]:
vector=CountVectorizer()
x=vector.fit_transform(x)

In [143]:
x=x.toarray()

In [144]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=4,stratify=y)

In [145]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((3633, 61425), (1212, 61425), (3633,), (1212,))

In [146]:
from sklearn.linear_model import LogisticRegression

In [147]:
linear=LogisticRegression()
linear.fit(x_train,y_train)

LogisticRegression()

In [148]:
pred=linear.predict(x_train)


In [149]:
pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [150]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [151]:
print(accuracy_score(pred,y_train))

0.9977979631158822


In [152]:
prediction=linear.predict(x_test)

In [153]:
print(accuracy_score(prediction,y_test))

0.981023102310231


In [154]:
confusion_matrix(prediction,y_test)

array([[679,  19],
       [  4, 510]], dtype=int64)

In [155]:
#[true,positive][false positive]
#[false,negative][false positive]

In [156]:
confusion_matrix(pred,y_train)

array([[2049,    8],
       [   0, 1576]], dtype=int64)

In [157]:
text=x_test[0]

preds=linear.predict([text])
print(preds)
if(preds==1):
    print("it is spam and it is fake")
else:
    print("it is ham and it is real news")

[1]
it is spam and it is fake


In [158]:
prediction

array([1, 1, 0, ..., 0, 0, 0], dtype=int64)

In [159]:
#vector.vocabulary_

In [160]:
#advantages of bow====>
#=>it is simple for implementation

#Disadvantages of bow ====>
#=>sparse matrix
#=>out of vocabulary
#=>semantic information cannot be captured
#=>cannot 
# fixed size array


In [161]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [162]:
#term_frequency and inverse_document_frequency using the same dataset
# previously used for countvectorizer 

In [163]:
data1=({"wealth":[ "hello how are you",
"hello what about you",
"hello what do want",
"i am good",
"i am fine",
"i am bad"],
"label":[0,0,0,1,1,1]})

In [164]:
df=pd.DataFrame(data1)
print(df)

                 wealth  label
0     hello how are you      0
1  hello what about you      0
2    hello what do want      0
3             i am good      1
4             i am fine      1
5              i am bad      1


In [165]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [166]:
tfidf=TfidfVectorizer(stop_words="english")

In [167]:
vector=tfidf.fit_transform(df["wealth"]).toarray()
vector

array([[0.        , 0.        , 0.        , 1.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        , 0.        ],
       [0.        , 0.        , 0.        , 0.56921261, 0.82219037],
       [0.        , 0.        , 1.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        , 0.        , 0.        ]])

In [168]:
tfidf.idf_

array([2.25276297, 2.25276297, 2.25276297, 1.55961579, 2.25276297])

In [169]:
vocab=tfidf.get_feature_names_out()
vocab

array(['bad', 'fine', 'good', 'hello', 'want'], dtype=object)

In [170]:
#formula for tf ===>(no of repetition of words in sentences/total.no.of words in sentences)

In [171]:
#formula for idf ===>log(total no of sentences/no of sentences containing the  word)

In [172]:
#advantages===>tf_idf
#1)simple to implement
#2)able to identify uniqueness and importance of words

In [173]:
#disadvantage===>tf_idf
#1)still sparsity exists
#2)oov

In [174]:
dataset1=pd.read_csv("C:\\Users\\user\\OneDrive\\Documents\\spamham.csv")

In [175]:
dataset1

Text  Class Label
0     Supply Quality China's EXCLUSIVE dimensions at...      1  spam
1                            over. SidLet me know. Thx.      0   ham
2     Dear Friend,Greetings to you.I wish to accost ...      1  spam
3     MR. CHEUNG PUIHANG SENG BANK LTD.DES VOEUX RD....      1  spam
4             Not a surprising assessment from Embassy.      0   ham
...                                                 ...    ...   ...
4840  It has been prepared- ready for your signature...      0   ham
4841                                     And to you too      0   ham
4842   <html><head><style>P{margin:0px;padding:0px}body      1  spam
4843  Robinson talking now voice cracking but resolu...      0   ham
4844  PIR <preines(Wednesday February 10 2010 1:16 P...      0   ham

[4845 rows x 3 columns]

In [176]:
dataset1.drop('Label',axis=1,inplace=True)

In [177]:
dataset1

Text  Class
0     Supply Quality China's EXCLUSIVE dimensions at...      1
1                            over. SidLet me know. Thx.      0
2     Dear Friend,Greetings to you.I wish to accost ...      1
3     MR. CHEUNG PUIHANG SENG BANK LTD.DES VOEUX RD....      1
4             Not a surprising assessment from Embassy.      0
...                                                 ...    ...
4840  It has been prepared- ready for your signature...      0
4841                                     And to you too      0
4842   <html><head><style>P{margin:0px;padding:0px}body      1
4843  Robinson talking now voice cracking but resolu...      0
4844  PIR <preines(Wednesday February 10 2010 1:16 P...      0

[4845 rows x 2 columns]

In [178]:
def remove(content):
    text=re.sub('[^a-zA-Z]',' ',content)
    text=text.lower()
    text=text.split()
    text=[stem.stem(word) for word in text if word not in stopwords.words("english")]
    review=' '.join(text)
    return review
        

In [179]:
dataset1["Text"]=dataset1["Text"].apply(remove)

In [180]:
dataset1["Text"]

0       suppli qualiti china exclus dimens unbeat pric...
1                                         sidlet know thx
2       dear friend greet wish accost request would im...
3       mr cheung puihang seng bank ltd de voeux rd br...
4                                  surpris assess embassi
                              ...                        
4840                       prepar readi signatur tomorrow
4841                                                     
4842              html head style p margin px pad px bodi
4843    robinson talk voic crack resolut carv stay fir...
4844    pir prein wednesday februari pmcdm huma abedin...
Name: Text, Length: 4845, dtype: object

In [181]:
X=dataset1["Text"]

In [182]:
Y=dataset1["Class"]

In [183]:
vectorizer=TfidfVectorizer(stop_words="english")
X=vectorizer.fit_transform(X)

In [184]:
X

<4845x61274 sparse matrix of type '<class 'numpy.float64'>'
	with 356413 stored elements in Compressed Sparse Row format>

In [185]:
xtrain,xtest,ytrain,ytest=train_test_split(X,Y,test_size=0.2,random_state=11,stratify=Y)

In [186]:
linreg=LogisticRegression()
linreg.fit(xtrain,ytrain)

LogisticRegression()

In [188]:
pred1=linreg.predict(xtrain)

In [189]:
pred2=linreg.predict(xtest)

In [190]:
print(accuracy_score(pred1,ytrain))

0.9858101135190919


In [191]:
print(accuracy_score(pred2,ytest))

0.9545923632610939


In [192]:
print(confusion_matrix(pred1,ytrain))

[[2185   54]
 [   1 1636]]


In [193]:
print(confusion_matrix(pred2,ytest))

[[545  43]
 [  1 380]]
