#gradient calculation single function

#adagrad

In [1]:
#form ==> x-->square-->y

In [2]:
import torch

In [3]:
x=torch.tensor(3,requires_grad=True,dtype=torch.float32)

In [4]:
y=x**2

In [5]:
#forward propagation
y

tensor(9., grad_fn=<PowBackward0>)

In [6]:
#derivative of y
y.backward()

In [7]:
x.grad

tensor(6.)

#gradient calculation using nested function

In [8]:
#form ==> x-->square-->y-->sin-->z

In [9]:
x=torch.tensor(3,requires_grad=True,dtype=torch.float32)

In [10]:
x

tensor(3., requires_grad=True)

In [11]:
y=x**2

In [12]:
z=torch.sin(y)

In [13]:
y

tensor(9., grad_fn=<PowBackward0>)

In [14]:
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [15]:
z.backward()

In [16]:
x.grad

tensor(-5.4668)

pytorch is actually creating a one graph in the backend

creating a simple neural network from scratch using pytorch

In [17]:
import torch.nn as nn

#Neural Network will be five inputs one hidden layer and one output

In [18]:
class model1(nn.Module):
    def __init__(self,new_features):
        super().__init__()
        self.linear=nn.Linear(new_features,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self,features):
        out=self.linear(features)
        out=self.sigmoid(out)
        return out

#creation of data

In [19]:
data=torch.rand(10,5)

In [20]:
data

tensor([[0.1791, 0.3366, 0.2891, 0.7827, 0.2534],
        [0.3606, 0.3925, 0.2607, 0.5291, 0.9215],
        [0.0859, 0.7432, 0.5431, 0.8506, 0.1759],
        [0.8208, 0.6642, 0.0298, 0.0392, 0.0439],
        [0.1343, 0.4876, 0.6808, 0.9901, 0.0073],
        [0.8035, 0.6830, 0.9967, 0.9872, 0.6823],
        [0.8624, 0.1091, 0.5111, 0.7724, 0.7345],
        [0.3689, 0.8066, 0.7248, 0.3600, 0.7149],
        [0.2167, 0.4181, 0.0563, 0.6221, 0.6714],
        [0.0259, 0.4135, 0.1189, 0.4570, 0.3524]])

In [21]:
data.shape[1]

5

In [22]:
obj=model1(data.shape[1])

In [23]:
obj(data)

tensor([[0.5190],
        [0.4670],
        [0.4684],
        [0.4966],
        [0.5012],
        [0.4412],
        [0.5159],
        [0.3972],
        [0.4961],
        [0.4942]], grad_fn=<SigmoidBackward0>)

In [24]:
obj.forward(data)

tensor([[0.5190],
        [0.4670],
        [0.4684],
        [0.4966],
        [0.5012],
        [0.4412],
        [0.5159],
        [0.3972],
        [0.4961],
        [0.4942]], grad_fn=<SigmoidBackward0>)

In [25]:
obj.linear.weight

Parameter containing:
tensor([[ 0.1304, -0.3631, -0.3072,  0.2473, -0.2363]], requires_grad=True)

In [26]:
obj.linear.bias

Parameter containing:
tensor([0.1302], requires_grad=True)

#Neural Network will five input three hidden layer and one output

#hidden layer -->reu 

#output layer -->sigmoid 

In [27]:
class model2(nn.Module):
    def __init__(self,new_features):
        super().__init__()
        self.linear1=nn.Linear(new_features,3)
        self.relu=nn.ReLU()
        self.linear2=nn.Linear(3,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self,features):
        out=self.linear1(features)
        out=self.relu(out)
        out=self.linear2(out)
        out=self.sigmoid(out)
        return out

In [28]:
data1=torch.rand(10,5)

In [29]:
data1.shape[1]

5

In [30]:
obj1=model2(data1.shape[1])

In [31]:
obj1

model2(
  (linear1): Linear(in_features=5, out_features=3, bias=True)
  (relu): ReLU()
  (linear2): Linear(in_features=3, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)

In [32]:
obj1(data1)

tensor([[0.3360],
        [0.3352],
        [0.3588],
        [0.3768],
        [0.3594],
        [0.3506],
        [0.3648],
        [0.3734],
        [0.3573],
        [0.3701]], grad_fn=<SigmoidBackward0>)

In [33]:
obj1.forward(data1)

tensor([[0.3360],
        [0.3352],
        [0.3588],
        [0.3768],
        [0.3594],
        [0.3506],
        [0.3648],
        [0.3734],
        [0.3573],
        [0.3701]], grad_fn=<SigmoidBackward0>)

#creation of inbuilt method  using the Sequential method in pytorch

In [34]:
import torch
import torch.nn as nn

class custom(nn.Module):
    def __init__(self,new_features):
        super().__init__()
        self.network=nn.Sequential(
            nn.Linear(new_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )
    
    def forward(self,features):
        out=self.network(features)
        return out

In [35]:
data1

tensor([[0.9521, 0.0502, 0.3523, 0.0239, 0.9612],
        [0.1285, 0.0932, 0.0945, 0.1971, 0.5636],
        [0.3137, 0.8438, 0.8661, 0.1732, 0.5831],
        [0.1029, 0.9801, 0.5232, 0.4802, 0.1498],
        [0.6839, 0.3009, 0.9350, 0.3230, 0.1852],
        [0.2472, 0.2714, 0.5333, 0.8518, 0.7140],
        [0.5292, 0.6569, 0.8710, 0.2737, 0.3421],
        [0.8294, 0.4037, 0.2560, 0.8958, 0.4608],
        [0.8394, 0.2050, 0.1657, 0.8093, 0.7685],
        [0.6469, 0.4683, 0.1596, 0.9163, 0.5410]])

In [36]:
obj2=custom(data1.shape[1])

In [37]:
obj2(data1)

tensor([[0.4734],
        [0.4502],
        [0.4547],
        [0.4488],
        [0.4703],
        [0.4793],
        [0.4624],
        [0.4877],
        [0.4901],
        [0.4830]], grad_fn=<SigmoidBackward0>)

In [38]:
obj2.forward(data1)

tensor([[0.4734],
        [0.4502],
        [0.4547],
        [0.4488],
        [0.4703],
        [0.4793],
        [0.4624],
        [0.4877],
        [0.4901],
        [0.4830]], grad_fn=<SigmoidBackward0>)

#using dataset  to perform the model creation

In [39]:
from sklearn import datasets
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [40]:
data2=datasets.load_breast_cancer()

In [41]:
data2

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [42]:
pf=pd.DataFrame(data=data2.data,columns=data2.feature_names)

In [43]:
pf["cancer"]=data2.target

In [44]:
pf.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  cancer  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [45]:
pf.tail()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
564                 0.05623  ...          26.40           166.10      2027.0   
565                 0.05533  ...          38.25           155.00      1731.0   
566                 0.05648  ...          34.12           126.70      1124.0   
567                 0.07016  ...          39.42           184.60      1821.0   
568                 0.05884  ...          30.37            59.16       268.6   

     worst smoothness  worst compactness  worst concavity  \
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     worst concave points  worst symmetry  worst fractal dimension  cancer  
564                0.2216          0.2060                  0.07115       0  
565                0.1628          0.2572                  0.06637       0  
566                0.1418          0.2218                  0.07820       0  
567                0.2650          0.4087                  0.12400       0  
568                0.0000          0.2871                  0.07039       1  

[5 rows x 31 columns]

In [46]:
pf.columns

Index(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error', 'fractal dimension error',
       'worst radius', 'worst texture', 'worst perimeter', 'worst area',
       'worst smoothness', 'worst compactness', 'worst concavity',
       'worst concave points', 'worst symmetry', 'worst fractal dimension',
       'cancer'],
      dtype='object')

In [47]:
pf.isnull().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
cancer                     0
dtype: int64

In [48]:
pf.shape[1]

31

In [49]:
x=pf.iloc[:,0:30]

In [50]:
x

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst radius  worst texture  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     worst perimeter  worst area  worst smoothness  worst compactness  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     worst concavity  worst concave points  worst symmetry  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [51]:
y=pf.loc[:,['cancer']]

In [52]:
y=np.array(y)

#0==>malignant cancer

#1==>benign no cancer

In [53]:

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=5,stratify=y)

In [54]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((455, 30), (114, 30), (455, 1), (114, 1))

In [55]:
x_train

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
508       16.300         15.70          104.70      819.8          0.09427   
524        9.847         15.68           63.00      293.2          0.09492   
161       19.190         15.94          126.30     1157.0          0.08694   
330       16.030         15.51          105.80      793.2          0.09491   
269       10.710         20.39           69.50      344.9          0.10820   
..           ...           ...             ...        ...              ...   
331       12.980         19.35           84.52      514.0          0.09579   
429       12.720         17.67           80.98      501.3          0.07896   
177       16.460         20.11          109.30      832.9          0.09831   
500       15.040         16.74           98.73      689.4          0.09883   
154       13.150         15.34           85.31      538.9          0.09384   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
508           0.06712         0.05526              0.04563         0.1711   
524           0.08419         0.02330              0.02416         0.1387   
161           0.11850         0.11930              0.09667         0.1741   
330           0.13710         0.12040              0.07041         0.1782   
269           0.12890         0.08448              0.02867         0.1668   
..                ...             ...                  ...            ...   
331           0.11250         0.07107              0.02950         0.1761   
429           0.04522         0.01402              0.01835         0.1459   
177           0.15560         0.17930              0.08866         0.1794   
500           0.13640         0.07721              0.06142         0.1668   
154           0.08498         0.09293              0.03483         0.1822   

     mean fractal dimension  ...  worst radius  worst texture  \
508                 0.05657  ...         17.32          17.76   
524                 0.06891  ...         11.24          22.99   
161                 0.05176  ...         22.03          17.81   
330                 0.05976  ...         18.76          21.98   
269                 0.06862  ...         11.69          25.21   
..                      ...  ...           ...            ...   
331                 0.06540  ...         14.42          21.95   
429                 0.05544  ...         13.82          20.96   
177                 0.06323  ...         17.79          28.45   
500                 0.06869  ...         16.76          20.43   
154                 0.06207  ...         14.77          20.50   

     worst perimeter  worst area  worst smoothness  worst compactness  \
508           109.80       928.2            0.1354            0.13610   
524            74.32       376.5            0.1419            0.22430   
161           146.60      1495.0            0.1124            0.20160   
330           124.30      1070.0            0.1435            0.44780   
269            76.51       410.4            0.1335            0.25500   
..               ...         ...               ...                ...   
331            99.21       634.3            0.1288            0.32530   
429            88.87       586.8            0.1068            0.09605   
177           123.50       981.2            0.1415            0.46670   
500           109.70       856.9            0.1135            0.21760   
154            97.67       677.3            0.1478            0.22560   

     worst concavity  worst concave points  worst symmetry  \
508          0.19470               0.13570          0.2300   
524          0.08434               0.06528          0.2502   
161          0.22640               0.17770          0.2443   
330          0.49560               0.19810          0.3019   
269          0.25340               0.08600          0.2605   
..               ...                   ...             ...   
331          0.34390               0.09858         

In [56]:
x_test

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
525        8.571         13.10           54.53      221.3          0.10360   
221       13.560         13.90           88.59      561.3          0.10510   
67        11.310         19.04           71.80      394.1          0.08139   
350       11.660         17.07           73.70      421.0          0.07561   
314        8.597         18.60           54.09      221.2          0.10740   
..           ...           ...             ...        ...              ...   
324       12.200         15.21           78.01      457.9          0.08673   
287       12.890         13.12           81.89      515.9          0.06955   
273        9.742         15.67           61.50      289.9          0.09037   
428       11.130         16.62           70.47      381.1          0.08151   
413       14.990         22.11           97.53      693.7          0.08515   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
525           0.07632        0.025650              0.01510         0.1678   
221           0.11920        0.078600              0.04451         0.1962   
67            0.04701        0.037090              0.02230         0.1516   
350           0.03630        0.008306              0.01162         0.1671   
314           0.05847        0.000000              0.00000         0.2163   
..                ...             ...                  ...            ...   
324           0.06545        0.019940              0.01692         0.1638   
287           0.03729        0.022600              0.01171         0.1337   
273           0.04689        0.011030              0.01407         0.2081   
428           0.03834        0.013690              0.01370         0.1511   
413           0.10250        0.068590              0.03876         0.1944   

     mean fractal dimension  ...  worst radius  worst texture  \
525                 0.07126  ...         9.473          18.45   
221                 0.06303  ...        14.980          17.13   
67                  0.05667  ...        12.330          23.84   
350                 0.05731  ...        13.280          19.74   
314                 0.07359  ...         8.952          22.44   
..                      ...  ...           ...            ...   
324                 0.06129  ...        13.750          21.38   
287                 0.05581  ...        13.620          15.54   
273                 0.06312  ...        10.750          20.88   
428                 0.06148  ...        11.680          20.29   
413                 0.05913  ...        16.760          31.55   

     worst perimeter  worst area  worst smoothness  worst compactness  \
525            63.30       275.6           0.16410            0.22350   
221           101.10       686.6           0.13760            0.26980   
67             78.00       466.7           0.12900            0.09148   
350            83.61       542.5           0.09958            0.06476   
314            56.65       240.1           0.13470            0.07767   
..               ...         ...               ...                ...   
324            91.11       583.1           0.12560            0.19280   
287            87.40       577.0           0.09616            0.11470   
273            68.09       355.2           0.14670            0.09370   
428            74.35       421.1           0.10300            0.06219   
413           110.20       867.1           0.10770            0.33450   

     worst concavity  worst concave points  worst symmetry  \
525          0.17540               0.08512          0.2983   
221          0.25770               0.09090          0.3065   
67           0.14440               0.06961          0.2400   
350          0.03046               0.04262          0.2731   
314          0.00000               0.00000          0.3142   
..               ...                   ...             ...   
324          0.11670               0.05556         

In [57]:
y_train

array([[1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [58]:
y_test

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
    

#Normalization of data

In [59]:
ss=StandardScaler()
x_train=ss.fit_transform(x_train)
x_test=ss.transform(x_test)

In [60]:
x_train

array([[ 0.60253271, -0.8501462 ,  0.51218608, ...,  0.33180835,
        -0.92375978, -0.61970534],
       [-1.24425787, -0.85495747, -1.22156067, ..., -0.76912058,
        -0.59680452,  0.46608523],
       [ 1.42962473, -0.79241096,  1.41024195, ...,  0.988426  ,
        -0.69230135, -1.15683974],
       ...,
       [ 0.64832327,  0.21073893,  0.70343872, ...,  1.39177684,
         0.29665738,  0.63616865],
       [ 0.24193204, -0.59996014,  0.26397342, ..., -0.1981759 ,
        -1.1228464 ,  0.10397215],
       [-0.29896897, -0.93674907, -0.29398537, ..., -0.26977849,
         1.58343676,  0.15005927]])

In [61]:
x_test

array([[-1.6094376 , -1.47561136, -1.57371498, ..., -0.45894691,
         0.18173747,  1.16891379],
       [-0.18163065, -1.28316054, -0.15761392, ..., -0.36858381,
         0.31446188, -0.10012794],
       [-0.82556042, -0.04666404, -0.85568605, ..., -0.70142643,
        -0.76190074, -0.94286383],
       ...,
       [-1.27430793, -0.85736311, -1.28392566, ..., -0.98314667,
        -0.04810237, -0.10122526],
       [-0.8770748 , -0.62882776, -0.91098301, ..., -1.15746302,
        -0.78941678, -0.7003578 ],
       [ 0.22762249,  0.69186598,  0.21408142, ...,  0.25520295,
         0.47308374,  0.48912879]])

In [62]:
y_train

array([[1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [63]:
y_test

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
    

#converting data into tensor array

In [64]:
x_train_tensor=torch.from_numpy(x_train.astype(np.float32))
x_test_tensor=torch.from_numpy(x_test.astype(np.float32))
y_train_tensor=torch.from_numpy(y_train.astype(np.float32))
y_test_tensor=torch.from_numpy(y_test.astype(np.float32))

In [65]:
x_test_tensor.dtype

torch.float32

In [66]:
class mymodel(nn.Module):
    def __init__(self,new_features):
        super().__init__()
        self.linear1=nn.Linear(new_features,3)
        self.relu=nn.ReLU()
        self.linear2=nn.Linear(3,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self,features):
        out=self.linear1(features)
        out=self.relu(out)
        out=self.linear2(out)
        out=self.sigmoid(out)
        return out

In [67]:
x_train_tensor.shape

torch.Size([455, 30])

In [68]:
s1=y_train_tensor.view(1,-1)

In [69]:
s1.shape

torch.Size([1, 455])

In [70]:
s2=y_train_tensor.view(-1,1)

In [71]:
s2.shape

torch.Size([455, 1])

In [72]:
learning_rate=0.1

In [73]:
epochs=35

In [74]:
x_train.shape[1]

30

In [75]:
object=mymodel(x_train.shape[1])

In [76]:
loss_function=nn.BCELoss()

In [77]:
optimizer=torch.optim.SGD(object.parameters(),lr=learning_rate)

In [78]:
for epoch in range(epochs):

    #forward pass
    y_pred=object(x_train_tensor)
    
    #loss calculation
    loss=loss_function(y_pred,y_train_tensor.view(-1,1))

    #clean gradients or reset process
    optimizer.zero_grad()
    
    #backward propagation
    loss.backward()
    
    #update step
    optimizer.step()

    print(f" {epoch+1},loss:{loss.item()}")


 1,loss:0.8374159336090088
 2,loss:0.7873173356056213
 3,loss:0.7476258277893066
 4,loss:0.7156693935394287
 5,loss:0.6897047162055969
 6,loss:0.6680086851119995
 7,loss:0.6496831774711609
 8,loss:0.6339374780654907
 9,loss:0.6196988821029663
 10,loss:0.6065792441368103
 11,loss:0.5942238569259644
 12,loss:0.5826246738433838
 13,loss:0.5717004537582397
 14,loss:0.5612579584121704
 15,loss:0.5512804388999939
 16,loss:0.5417986512184143
 17,loss:0.5326260924339294
 18,loss:0.5237278342247009
 19,loss:0.5150778889656067
 20,loss:0.5067756175994873
 21,loss:0.4987671673297882
 22,loss:0.4909780025482178
 23,loss:0.483439564704895
 24,loss:0.47611093521118164
 25,loss:0.4689793586730957
 26,loss:0.46203264594078064
 27,loss:0.45525726675987244
 28,loss:0.44865408539772034
 29,loss:0.44219911098480225
 30,loss:0.43590033054351807
 31,loss:0.42976048588752747
 32,loss:0.42378556728363037
 33,loss:0.41798150539398193
 34,loss:0.4123299717903137
 35,loss:0.4068180024623871


In [79]:
from torchinfo import summary

In [80]:
x_train_tensor.shape

torch.Size([455, 30])

In [81]:
summary(object,input_size=(455,30))

Layer (type:depth-idx)                   Output Shape              Param #
mymodel                                  [455, 1]                  --
├─Linear: 1-1                            [455, 3]                  93
├─ReLU: 1-2                              [455, 3]                  --
├─Linear: 1-3                            [455, 1]                  4
├─Sigmoid: 1-4                           [455, 1]                  --
Total params: 97
Trainable params: 97
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.04
Input size (MB): 0.05
Forward/backward pass size (MB): 0.01
Params size (MB): 0.00
Estimated Total Size (MB): 0.07

In [82]:
pred1=object(x_test_tensor[0])

In [83]:
(pred1>0.5).float()

tensor([1.])

In [84]:
y_test_tensor[1]

tensor([1.])

In [85]:
actual=y_test_tensor[1]

In [86]:
(pred1==actual).float().mean()

tensor(0.)

In [87]:
with torch.no_grad():
    y_pred=object(x_test_tensor)
    y_pred=(y_pred>0.5).float()
    accuracy=(y_pred==y_test_tensor).float().mean()
    print(f"the accuracy is : {accuracy.item()}")

the accuracy is : 0.9912280440330505


In [88]:
#Dataset    ==> for initialization only

#DataLoader ==> for sending data batchs

#creation of dummy datasets

In [89]:
from sklearn.datasets import make_classification
import torch

In [90]:
x,y=make_classification(
                        n_samples=20,   # no of datas or samples
                        n_features=3,   # no of  columns
                        n_informative=2,#no of informatives
                        n_redundant=0,   #no reduntant in the datas
                        n_classes=2,    #no classes in your label
                        random_state=20 #for reproducability
                        )

In [91]:
x

array([[-1.92340582,  0.36302116,  0.52772847],
       [ 0.35570789,  0.1384218 , -0.96221598],
       [ 0.52777027,  0.42108815, -0.48245091],
       [-1.57257964,  0.26749034,  0.15583822],
       [ 1.34977647, -1.01834071,  0.09878861],
       [-1.44465381, -0.35674894, -1.48238505],
       [-0.1277233 ,  1.26247643,  1.3014294 ],
       [-0.8463147 , -1.46683756, -0.85616422],
       [ 0.73268863, -0.98972705, -1.48571961],
       [-1.10201218,  1.10557442,  0.1140476 ],
       [-0.33223102, -1.6432131 , -0.21966112],
       [ 1.41891414, -1.13599391,  2.09466534],
       [ 0.32626954,  1.47708907, -0.51314511],
       [ 0.53801084,  1.55376789, -0.22832103],
       [ 0.93928588, -1.07485961,  0.69100212],
       [ 1.85971768,  0.63245719, -0.85477549],
       [-0.48171213, -1.41999374, -0.82869277],
       [-0.18163665,  1.71401726, -0.99480191],
       [-1.86506731, -0.81756028,  1.50339816],
       [ 1.17027916, -0.63548335,  0.35942899]])

In [92]:
y

array([1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0])

In [93]:
x=torch.tensor(x,dtype=torch.float32)
y=torch.tensor(y,dtype=torch.float32)

In [94]:
x.dtype

torch.float32

In [95]:
y.dtype

torch.float32

#Example of Dataset

In [96]:
from torch.utils.data import DataLoader,Dataset

In [97]:
class mass(Dataset):
    def __init__(self,features,labels):
        self.features=features
        self.labels=labels
        
    #dunder methods or special methods in python 
    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self, index):
        return self.features[index],self.labels[index]

In [98]:
mas=mass(x,y)

In [99]:
len(mas)

20

In [100]:
mas[2]

(tensor([ 0.5278,  0.4211, -0.4825]), tensor(1.))

#Example of DataLoader

In [101]:
dataloader=DataLoader(mas,batch_size=2,shuffle=False)

In [102]:
print(dataloader)

In [103]:
for batch_data,batch_labels in dataloader:
    print(f"{batch_data}")
    print(f" {batch_labels}")
    print("-"*50)


tensor([[-1.9234,  0.3630,  0.5277],
        [ 0.3557,  0.1384, -0.9622]])
 tensor([1., 1.])
--------------------------------------------------
tensor([[ 0.5278,  0.4211, -0.4825],
        [-1.5726,  0.2675,  0.1558]])
 tensor([1., 1.])
--------------------------------------------------
tensor([[ 1.3498, -1.0183,  0.0988],
        [-1.4447, -0.3567, -1.4824]])
 tensor([0., 0.])
--------------------------------------------------
tensor([[-0.1277,  1.2625,  1.3014],
        [-0.8463, -1.4668, -0.8562]])
 tensor([1., 0.])
--------------------------------------------------
tensor([[ 0.7327, -0.9897, -1.4857],
        [-1.1020,  1.1056,  0.1140]])
 tensor([0., 1.])
--------------------------------------------------
tensor([[-0.3322, -1.6432, -0.2197],
        [ 1.4189, -1.1360,  2.0947]])
 tensor([0., 0.])
--------------------------------------------------
tensor([[ 0.3263,  1.4771, -0.5131],
        [ 0.5380,  1.5538, -0.2283]])
 tensor([1., 1.])
-------------------------------------------