In [1]:
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import torch
import torch.nn as nn
from torch.utils.data import DataLoader,Dataset
import torch.optim as optim
import pandas as pd
import numpy as np

In [2]:
data=datasets.load_iris()

In [3]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
df=pd.DataFrame(data=data.data,columns=data.feature_names)
df["label"]=data.target

In [5]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  
0      0  
1      0  
2      0  
3      0  
4      0

In [6]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
label                0
dtype: int64

In [7]:
df['label'].value_counts()

label
0    50
1    50
2    50
Name: count, dtype: int64

In [8]:
df["label"].unique()

array([0, 1, 2])

In [9]:
x=df.iloc[:,0:4]

In [10]:
x

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [11]:
y=np.array(df['label'])

In [12]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,stratify=y)

In [14]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((120, 4), (30, 4), (120,), (30,))

In [15]:
ss=StandardScaler()
x_train=ss.fit_transform(x_train)
x_test=ss.transform(x_test)

In [16]:
x_train

array([[ 0.51692823, -1.75457397,  0.35248355,  0.12419185],
       [-0.07952742,  2.06541632, -1.44743244, -1.31381903],
       [ 0.99409276,  0.04306852,  0.52122567,  0.38564837],
       [-1.63031212, -1.75457397, -1.39118506, -1.18309077],
       [-0.79527421,  0.71718445, -1.33493769, -1.31381903],
       [ 0.99409276,  0.49247914,  1.08369941,  1.69293099],
       [ 0.03976371,  0.26777383,  0.57747304,  0.77783316],
       [-0.07952742, -1.08045804,  0.12749405, -0.00653641],
       [ 0.51692823,  0.49247914,  0.52122567,  0.51637664],
       [-0.91456534,  1.6160057 , -1.27869031, -1.18309077],
       [-1.03385647, -1.75457397, -0.26623757, -0.26799294],
       [ 0.63621937,  0.26777383,  0.40873092,  0.38564837],
       [-1.1531476 , -1.30516335,  0.40873092,  0.6471049 ],
       [-0.91456534,  1.6160057 , -1.22244294, -1.31381903],
       [ 0.7555105 , -0.18163679,  1.13994679,  1.30074621],
       [-0.19881855, -0.63104742,  0.40873092,  0.12419185],
       [ 1.47125728, -0.

In [17]:
x_test

array([[-1.03385647,  0.94188976, -1.22244294, -0.79090599],
       [-0.31810968, -1.30516335,  0.07124667, -0.13726468],
       [ 0.3976371 , -0.63104742,  0.57747304,  0.77783316],
       [ 0.51692823, -1.30516335,  0.63372042,  0.38564837],
       [-0.43740081, -1.30516335,  0.12749405,  0.12419185],
       [ 0.51692823,  0.49247914,  1.25244154,  1.69293099],
       [-1.27243873,  0.71718445, -1.05370081, -1.31381903],
       [ 0.7555105 ,  0.26777383,  0.74621517,  1.03928968],
       [-1.1531476 ,  0.04306852, -1.27869031, -1.4445473 ],
       [ 0.15905484, -1.97927928,  0.12749405, -0.26799294],
       [-0.91456534,  0.49247914, -1.16619556, -0.92163425],
       [-0.91456534,  1.6160057 , -1.05370081, -1.05236251],
       [ 0.51692823, -0.4063421 ,  1.02745204,  0.77783316],
       [ 0.99409276, -1.30516335,  1.13994679,  0.77783316],
       [ 1.11338389,  0.26777383,  1.19619416,  1.43147447],
       [ 0.27834597, -0.18163679,  0.4649783 ,  0.25492011],
       [ 0.87480163, -0.

In [18]:
x_train_tensor=torch.tensor(x_train,dtype=torch.float32)
x_test_tensor=torch.tensor(x_test,dtype=torch.float32)
y_train_tensor=torch.tensor(y_train,dtype=torch.float32)
y_test_tensor=torch.tensor(y_test,dtype=torch.float32)

In [19]:
x_train_tensor

tensor([[ 0.5169, -1.7546,  0.3525,  0.1242],
        [-0.0795,  2.0654, -1.4474, -1.3138],
        [ 0.9941,  0.0431,  0.5212,  0.3856],
        [-1.6303, -1.7546, -1.3912, -1.1831],
        [-0.7953,  0.7172, -1.3349, -1.3138],
        [ 0.9941,  0.4925,  1.0837,  1.6929],
        [ 0.0398,  0.2678,  0.5775,  0.7778],
        [-0.0795, -1.0805,  0.1275, -0.0065],
        [ 0.5169,  0.4925,  0.5212,  0.5164],
        [-0.9146,  1.6160, -1.2787, -1.1831],
        [-1.0339, -1.7546, -0.2662, -0.2680],
        [ 0.6362,  0.2678,  0.4087,  0.3856],
        [-1.1531, -1.3052,  0.4087,  0.6471],
        [-0.9146,  1.6160, -1.2224, -1.3138],
        [ 0.7555, -0.1816,  1.1399,  1.3007],
        [-0.1988, -0.6310,  0.4087,  0.1242],
        [ 1.4713, -0.1816,  1.1962,  1.1700],
        [ 0.3976, -1.9793,  0.4087,  0.3856],
        [-1.2724, -0.1816, -1.3349, -1.1831],
        [-0.7953,  2.2901, -1.2787, -1.4445],
        [ 0.9941,  0.4925,  1.0837,  1.1700],
        [-1.3917,  0.2678, -1.3912

In [20]:
x_test

array([[-1.03385647,  0.94188976, -1.22244294, -0.79090599],
       [-0.31810968, -1.30516335,  0.07124667, -0.13726468],
       [ 0.3976371 , -0.63104742,  0.57747304,  0.77783316],
       [ 0.51692823, -1.30516335,  0.63372042,  0.38564837],
       [-0.43740081, -1.30516335,  0.12749405,  0.12419185],
       [ 0.51692823,  0.49247914,  1.25244154,  1.69293099],
       [-1.27243873,  0.71718445, -1.05370081, -1.31381903],
       [ 0.7555105 ,  0.26777383,  0.74621517,  1.03928968],
       [-1.1531476 ,  0.04306852, -1.27869031, -1.4445473 ],
       [ 0.15905484, -1.97927928,  0.12749405, -0.26799294],
       [-0.91456534,  0.49247914, -1.16619556, -0.92163425],
       [-0.91456534,  1.6160057 , -1.05370081, -1.05236251],
       [ 0.51692823, -0.4063421 ,  1.02745204,  0.77783316],
       [ 0.99409276, -1.30516335,  1.13994679,  0.77783316],
       [ 1.11338389,  0.26777383,  1.19619416,  1.43147447],
       [ 0.27834597, -0.18163679,  0.4649783 ,  0.25492011],
       [ 0.87480163, -0.

In [21]:
y_train_tensor.shape

torch.Size([120])

In [22]:
y_test_tensor.shape

torch.Size([30])

In [23]:
class model(nn.Module):
    def __init__(self, new_features):
        super().__init__()
        self.linear1=nn.Linear(new_features,3)
        self.relu=nn.ReLU()
        self.linear2=nn.Linear(3,1)
    
    def forward(self,features):
        out=self.linear1(features)
        out=self.relu(out)
        out=self.linear2(out)
        return out

In [24]:
x_train.shape[1]

4

In [25]:
object=model(x_train.shape[1])

In [26]:
class custombatch(Dataset):
    def __init__(self,features,label):
        self.features=features
        self.label=label

    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self, index):
        return self.features[index],self.label[index]

In [27]:
dataset1=custombatch(x_train_tensor,y_train_tensor)
dataset2=custombatch(x_test_tensor,y_test_tensor)

In [28]:
len(dataset1)

120

In [29]:
dataset1[2]

(tensor([0.9941, 0.0431, 0.5212, 0.3856]), tensor(1.))

In [30]:
train_dataset=DataLoader(dataset1,batch_size=10,shuffle=True)
test_dataset=DataLoader(dataset2,batch_size=10,shuffle=False)

In [31]:
learning_rate=0.1

In [32]:
epochs=20

In [33]:
loss_function=nn.CrossEntropyLoss()

In [34]:
optimizer=optim.SGD(object.parameters(),lr=learning_rate)

In [35]:
for epoch in range(epochs):
    loss_calculate=0
    for batch_data,batch_label in train_dataset:
        input=batch_data
        label=batch_label

        y_pred=object(input)

        loss=loss_function(y_pred,label.view(-1,1))

        optimizer.zero_grad()

        loss.backward()

        optimizer.step()

        loss_calculate=loss_calculate+loss.item()
        print(loss_calculate)
    print(f"{epoch+1} : {loss_calculate/len(x_train_tensor)}")


0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1 : 0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2 : 0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3 : 0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
4 : 0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
5 : 0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
6 : 0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
7 : 0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
8 : 0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
9 : 0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
10 : 0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
11 : 0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
12 : 0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
13 : 0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
14 : 0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
15 : 0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
16 : 0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
17 : 0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


In [36]:
len(x_test_tensor)

30

In [37]:
y_test_tensor

tensor([0., 1., 2., 1., 1., 2., 0., 2., 0., 1., 0., 0., 2., 2., 2., 1., 1., 2.,
        2., 2., 0., 0., 1., 1., 0., 0., 1., 2., 0., 1.])

In [38]:
prediction=object(x_test_tensor[4])

In [39]:
prediction

tensor([-0.0605], grad_fn=<ViewBackward0>)

In [40]:
y_test_tensor[4]

tensor(1.)

In [41]:
with torch.no_grad():
    for batch_data,batch_label in test_dataset:
        input=batch_data
        label=batch_label
        y_pred=object(input)
        print(y_pred)

tensor([[-0.1114],
        [-0.0355],
        [-0.3536],
        [-0.2667],
        [-0.0605],
        [-0.5316],
        [-0.0650],
        [-0.4230],
        [ 0.0804],
        [ 0.0108]])
tensor([[-0.0453],
        [-0.2068],
        [-0.3581],
        [-0.4297],
        [-0.5425],
        [-0.2174],
        [-0.2563],
        [-0.4109],
        [-0.4106],
        [-0.5649]])
tensor([[ 0.0652],
        [-0.0581],
        [-0.2229],
        [ 0.0754],
        [ 0.1146],
        [ 0.0715],
        [-0.1623],
        [-0.4343],
        [ 0.0523],
        [ 0.0558]])
