#pytorch basics

#whatever operation we have been perform in the numpy library

#the same opertion we can able to perform in the torch

In [74]:
import torch

In [75]:
print(torch.__version__)

2.5.1+cpu


In [76]:
if torch.cuda.is_available():
    print('cuda')
    print(torch.cuda.get_device_name(0))

In [77]:
a=torch.empty(2,3)

In [78]:
print(a)

tensor([[2.3694e-38, 2.3694e-38, 2.3694e-38],
        [2.3694e-38, 2.3694e-38, 2.3694e-38]])


In [79]:
type(a)

torch.Tensor

In [80]:
a.fill_(2)

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [81]:
torch.zero_(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [82]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [83]:
torch.ones_like(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [84]:
torch.rand(2,2)

tensor([[0.8813, 0.3216],
        [0.2604, 0.2566]])

In [85]:
torch.rand(2,2)#it can change the matrix value when you

tensor([[0.1872, 0.6423],
        [0.1786, 0.1435]])

In [86]:
torch.manual_seed(12)
torch.rand(2,2)

tensor([[0.4657, 0.2328],
        [0.4527, 0.5871]])

#manaul_seed can maintain the same state

In [87]:
torch.manual_seed(12)
torch.rand(2,2)

tensor([[0.4657, 0.2328],
        [0.4527, 0.5871]])

In [88]:
two=torch.tensor([[1,2,3],[4,5,6]])
print(two)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [89]:
#syntax for arange(start,stop,step) last value will be excluded
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

In [92]:
torch.linspace(0,1,10) #it sets a boundary between 0 and 1 it create 10 values

tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])

In [93]:
torch.eye(5,5)# used create identical matrix

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [94]:
torch.full((2,2),5)

tensor([[5, 5],
        [5, 5]])

In [95]:
x=torch.tensor([[1,2,3],[3,4,5],[6,7,8]])

In [96]:
print(x)

tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])


In [97]:
print(x.shape)

torch.Size([3, 3])


In [98]:
torch.empty_like(x)

tensor([[6410931014304,             0,             0],
        [            0,             0,             0],
        [            0,             0,             0]])

In [99]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [100]:
torch.zeros(5)

tensor([0., 0., 0., 0., 0.])

In [101]:
torch.zero_(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [102]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.4086, 0.1272, 0.6373],
        [0.2421, 0.7312, 0.7224],
        [0.1992, 0.6948, 0.5830]])

In [103]:
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [104]:
x=x+2

In [105]:
x*2

tensor([[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]])

In [106]:
x/2

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [107]:
c=torch.tensor([-1,2,-3,4])

In [108]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [109]:
torch.neg(c)

tensor([ 1, -2,  3, -4])

In [110]:
d=torch.tensor([1.9,2.4,4.8,3.5])

In [111]:
torch.round(d)

tensor([2., 2., 5., 4.])

In [112]:
torch.floor(d)

tensor([1., 2., 4., 3.])

In [113]:
torch.ceil(d)

tensor([2., 3., 5., 4.])

In [114]:
c=torch.randint(size=(2,3),low=0,high=10)

In [115]:
c

tensor([[5, 9, 1],
        [2, 7, 8]])

In [116]:
torch.sum(c)

tensor(32)

In [117]:
torch.sum(c,dim=0)#0 means columns wise vertically it can sum it

tensor([ 7, 16,  9])

In [118]:
torch.sum(c,dim=1)#1 means row wise vertically it can sum it

tensor([15, 17])

In [119]:
torch.tensor(c,dtype=torch.float32)#change the datatype to float and printing the value 

C:\Users\user\AppData\Local\Temp\ipykernel_7272\2399469833.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.tensor(c,dtype=torch.float32)#change the datatype to float and printing the value


tensor([[5., 9., 1.],
        [2., 7., 8.]])

In [120]:
torch.mean(c,dim=1,dtype=torch.float32)

tensor([5.0000, 5.6667])

In [121]:
torch.max(c)

tensor(9)

In [122]:
torch.min(c)

tensor(1)

In [123]:
c

tensor([[5, 9, 1],
        [2, 7, 8]])

In [124]:
#argmax return the index of highest value in the given matix
torch.argmax(c)

tensor(1)

In [125]:
#argmin return the index of lowest value in the given matix
torch.argmin(c)

tensor(2)

In [126]:
n=torch.tensor([[6,3,8],[9,4,5]])

In [127]:
print(n)

tensor([[6, 3, 8],
        [9, 4, 5]])


In [147]:
#argmax with dim
torch.argmax(n,dim=0)

tensor([1, 1, 0])

In [150]:
#argmin with dim
torch.argmin(n,dim=1)

tensor([1, 1])

In [130]:
f=torch.randint(size=(2,3),low=0,high=10)
print(f)

tensor([[8, 2, 9],
        [2, 4, 7]])


In [131]:
g=torch.randint(size=(3,2),low=0,high=10)S
print(g)

tensor([[8, 7],
        [1, 8],
        [6, 9]])


In [132]:
c=torch.matmul(f,g)

In [133]:
c

tensor([[120, 153],
        [ 62, 109]])

In [134]:
a=torch.tensor([1,2])

In [135]:
b=torch.tensor([3,4])

In [136]:
torch.dot(a,b)

tensor(11)

In [137]:
g

tensor([[8, 7],
        [1, 8],
        [6, 9]])

In [138]:
torch.transpose(g,0,1)

tensor([[8, 1, 6],
        [7, 8, 9]])

In [139]:
c=torch.tensor([[1,2],[4,5]],dtype=torch.float32)

In [140]:
torch.inverse(c)

tensor([[-1.6667,  0.6667],
        [ 1.3333, -0.3333]])

In [141]:
torch.log(c)

tensor([[0.0000, 0.6931],
        [1.3863, 1.6094]])

In [142]:
torch.exp(c)

tensor([[  2.7183,   7.3891],
        [ 54.5981, 148.4132]])

In [143]:
torch.softmax(c,0)

tensor([[0.0474, 0.0474],
        [0.9526, 0.9526]])

In [144]:
torch.softmax(c,1)

tensor([[0.2689, 0.7311],
        [0.2689, 0.7311]])