#gradient calculation single function

In [523]:
#form ==> x-->square-->y

In [524]:
import torch

In [525]:
x=torch.tensor(3,requires_grad=True,dtype=torch.float32)

In [526]:
y=x**2

In [527]:
#forward propagation
y

tensor(9., grad_fn=<PowBackward0>)

In [528]:
#derivative of y
y.backward()

In [529]:
x.grad

tensor(6.)

#gradient calculation using nested function

In [530]:
#form ==> x-->square-->y-->sin-->z

In [531]:
x=torch.tensor(3,requires_grad=True,dtype=torch.float32)

In [532]:
x

tensor(3., requires_grad=True)

In [533]:
y=x**2

In [534]:
z=torch.sin(y)

In [535]:
y

tensor(9., grad_fn=<PowBackward0>)

In [536]:
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [537]:
z.backward()

In [538]:
x.grad

tensor(-5.4668)

pytorch is actually creating a one graph in the backend

creating a simple neural network from scratch using pytorch

In [539]:
import torch.nn as nn

#Neural Network will be five inputs one hidden layer and one output

In [540]:
class model1(nn.Module):
    def __init__(self,new_features):
        super().__init__()
        self.linear=nn.Linear(new_features,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self,features):
        out=self.linear(features)
        out=self.sigmoid(out)
        return out

#creation of data

In [541]:
data=torch.rand(10,5)

In [542]:
data

tensor([[0.9635, 0.3533, 0.4746, 0.8527, 0.5379],
        [0.3864, 0.5826, 0.1110, 0.3183, 0.1051],
        [0.0446, 0.1263, 0.9793, 0.5490, 0.4526],
        [0.7495, 0.9479, 0.9178, 0.0822, 0.6906],
        [0.4149, 0.2414, 0.0512, 0.9834, 0.2900],
        [0.2661, 0.3643, 0.6151, 0.9263, 0.1971],
        [0.9747, 0.5037, 0.0171, 0.3135, 0.1477],
        [0.1613, 0.2905, 0.8277, 0.1789, 0.6187],
        [0.4641, 0.8895, 0.2785, 0.1648, 0.4379],
        [0.1051, 0.9250, 0.2741, 0.3871, 0.1508]])

In [543]:
data.shape[1]

5

In [544]:
obj=model1(data.shape[1])

In [545]:
obj(data)

tensor([[0.3743],
        [0.4123],
        [0.3563],
        [0.2940],
        [0.4162],
        [0.3810],
        [0.4369],
        [0.3425],
        [0.3463],
        [0.3594]], grad_fn=<SigmoidBackward0>)

In [546]:
obj.forward(data)

tensor([[0.3743],
        [0.4123],
        [0.3563],
        [0.2940],
        [0.4162],
        [0.3810],
        [0.4369],
        [0.3425],
        [0.3463],
        [0.3594]], grad_fn=<SigmoidBackward0>)

In [547]:
obj.linear.weight

Parameter containing:
tensor([[ 0.1160, -0.3751, -0.2284, -0.0705, -0.4423]], requires_grad=True)

In [548]:
obj.linear.bias

Parameter containing:
tensor([-0.0865], requires_grad=True)

#Neural Network will five input three hidden layer and one output

#hidden layer -->reu 

#output layer -->sigmoid 

In [549]:
class model2(nn.Module):
    def __init__(self,new_features):
        super().__init__()
        self.linear1=nn.Linear(new_features,3)
        self.relu=nn.ReLU()
        self.linear2=nn.Linear(3,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self,features):
        out=self.linear1(features)
        out=self.relu(out)
        out=self.linear2(out)
        out=self.sigmoid(out)
        return out

In [550]:
data1=torch.rand(10,5)

In [551]:
data1.shape[1]

5

In [552]:
obj1=model2(data1.shape[1])

In [553]:
obj1

model2(
  (linear1): Linear(in_features=5, out_features=3, bias=True)
  (relu): ReLU()
  (linear2): Linear(in_features=3, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)

In [554]:
obj1(data1)

tensor([[0.5706],
        [0.5634],
        [0.5635],
        [0.5733],
        [0.5736],
        [0.5634],
        [0.5669],
        [0.5683],
        [0.5573],
        [0.5598]], grad_fn=<SigmoidBackward0>)

In [555]:
obj1.forward(data1)

tensor([[0.5706],
        [0.5634],
        [0.5635],
        [0.5733],
        [0.5736],
        [0.5634],
        [0.5669],
        [0.5683],
        [0.5573],
        [0.5598]], grad_fn=<SigmoidBackward0>)

#creation of inbuilt method  using the Sequential method in pytorch

In [556]:
import torch
import torch.nn as nn

class custom(nn.Module):
    def __init__(self,new_features):
        super().__init__()
        self.network=nn.Sequential(
            nn.Linear(new_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )
    
    def forward(self,features):
        out=self.network(features)
        return out

In [557]:
data1

tensor([[0.3667, 0.7574, 0.4872, 0.6693, 0.3801],
        [0.9643, 0.5469, 0.5784, 0.2485, 0.1483],
        [0.2012, 0.8172, 0.3828, 0.2497, 0.1068],
        [0.5691, 0.3763, 0.0508, 0.6898, 0.5635],
        [0.7962, 0.1707, 0.7528, 0.4973, 0.1660],
        [0.5759, 0.6345, 0.3523, 0.4693, 0.6162],
        [0.6384, 0.9715, 0.1525, 0.8013, 0.2142],
        [0.4036, 0.8086, 0.6568, 0.6012, 0.8208],
        [0.1806, 0.8593, 0.5284, 0.0467, 0.7799],
        [0.5616, 0.7185, 0.4547, 0.1144, 0.2351]])

In [558]:
obj2=custom(data1.shape[1])

In [559]:
obj2(data1)

tensor([[0.7371],
        [0.7107],
        [0.7124],
        [0.7010],
        [0.7128],
        [0.7182],
        [0.7364],
        [0.7480],
        [0.7182],
        [0.7065]], grad_fn=<SigmoidBackward0>)

In [560]:
obj2.forward(data1)

tensor([[0.7371],
        [0.7107],
        [0.7124],
        [0.7010],
        [0.7128],
        [0.7182],
        [0.7364],
        [0.7480],
        [0.7182],
        [0.7065]], grad_fn=<SigmoidBackward0>)

#using dataset  to perform the model creation

In [561]:
from sklearn import datasets
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [562]:
data2=datasets.load_breast_cancer()

In [563]:
data2

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [564]:
pf=pd.DataFrame(data=data2.data,columns=data2.feature_names)

In [565]:
pf["cancer"]=data2.target

In [566]:
pf.head()

mean radius  mean texture  ...  worst fractal dimension  cancer
0        17.99         10.38  ...                  0.11890       0
1        20.57         17.77  ...                  0.08902       0
2        19.69         21.25  ...                  0.08758       0
3        11.42         20.38  ...                  0.17300       0
4        20.29         14.34  ...                  0.07678       0

[5 rows x 31 columns]

In [567]:
pf.tail()

mean radius  mean texture  ...  worst fractal dimension  cancer
564        21.56         22.39  ...                  0.07115       0
565        20.13         28.25  ...                  0.06637       0
566        16.60         28.08  ...                  0.07820       0
567        20.60         29.33  ...                  0.12400       0
568         7.76         24.54  ...                  0.07039       1

[5 rows x 31 columns]

In [568]:
pf.columns

Index(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error', 'fractal dimension error',
       'worst radius', 'worst texture', 'worst perimeter', 'worst area',
       'worst smoothness', 'worst compactness', 'worst concavity',
       'worst concave points', 'worst symmetry', 'worst fractal dimension',
       'cancer'],
      dtype='object')

In [569]:
pf.isnull().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
cancer                     0
dtype: int64

In [570]:
pf.shape[1]

31

In [571]:
x=pf.iloc[:,0:30]

In [572]:
x

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0          17.99         10.38  ...          0.4601                  0.11890
1          20.57         17.77  ...          0.2750                  0.08902
2          19.69         21.25  ...          0.3613                  0.08758
3          11.42         20.38  ...          0.6638                  0.17300
4          20.29         14.34  ...          0.2364                  0.07678
..           ...           ...  ...             ...                      ...
564        21.56         22.39  ...          0.2060                  0.07115
565        20.13         28.25  ...          0.2572                  0.06637
566        16.60         28.08  ...          0.2218                  0.07820
567        20.60         29.33  ...          0.4087                  0.12400
568         7.76         24.54  ...          0.2871                  0.07039

[569 rows x 30 columns]

In [573]:
y=pf.loc[:,['cancer']]

In [574]:
y=np.array(y)

#0==>malignant cancer

#1==>benign no cancer

In [575]:

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=5,stratify=y)

In [576]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((455, 30), (114, 30), (455, 1), (114, 1))

In [577]:
x_train

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
508       16.300         15.70  ...          0.2300                  0.07230
524        9.847         15.68  ...          0.2502                  0.09209
161       19.190         15.94  ...          0.2443                  0.06251
330       16.030         15.51  ...          0.3019                  0.09124
269       10.710         20.39  ...          0.2605                  0.08701
..           ...           ...  ...             ...                      ...
331       12.980         19.35  ...          0.3596                  0.09166
429       12.720         17.67  ...          0.2165                  0.06025
177       16.460         20.11  ...          0.3054                  0.09519
500       15.040         16.74  ...          0.2177                  0.08549
154       13.150         15.34  ...          0.3849                  0.08633

[455 rows x 30 columns]

In [578]:
x_test

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
525        8.571         13.10  ...          0.2983                  0.10490
221       13.560         13.90  ...          0.3065                  0.08177
67        11.310         19.04  ...          0.2400                  0.06641
350       11.660         17.07  ...          0.2731                  0.06825
314        8.597         18.60  ...          0.3142                  0.08116
..           ...           ...  ...             ...                      ...
324       12.200         15.21  ...          0.2661                  0.07961
287       12.890         13.12  ...          0.2309                  0.06915
273        9.742         15.67  ...          0.2841                  0.08175
428       11.130         16.62  ...          0.2383                  0.07083
413       14.990         22.11  ...          0.3163                  0.09251

[114 rows x 30 columns]

In [579]:
y_train

array([[1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [580]:
y_test

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
    

#Normalization of data

In [581]:
ss=StandardScaler()
x_train=ss.fit_transform(x_train)
x_test=ss.transform(x_test)

In [582]:
x_train

array([[ 0.60253271, -0.8501462 ,  0.51218608, ...,  0.33180835,
        -0.92375978, -0.61970534],
       [-1.24425787, -0.85495747, -1.22156067, ..., -0.76912058,
        -0.59680452,  0.46608523],
       [ 1.42962473, -0.79241096,  1.41024195, ...,  0.988426  ,
        -0.69230135, -1.15683974],
       ...,
       [ 0.64832327,  0.21073893,  0.70343872, ...,  1.39177684,
         0.29665738,  0.63616865],
       [ 0.24193204, -0.59996014,  0.26397342, ..., -0.1981759 ,
        -1.1228464 ,  0.10397215],
       [-0.29896897, -0.93674907, -0.29398537, ..., -0.26977849,
         1.58343676,  0.15005927]])

In [583]:
x_test

array([[-1.6094376 , -1.47561136, -1.57371498, ..., -0.45894691,
         0.18173747,  1.16891379],
       [-0.18163065, -1.28316054, -0.15761392, ..., -0.36858381,
         0.31446188, -0.10012794],
       [-0.82556042, -0.04666404, -0.85568605, ..., -0.70142643,
        -0.76190074, -0.94286383],
       ...,
       [-1.27430793, -0.85736311, -1.28392566, ..., -0.98314667,
        -0.04810237, -0.10122526],
       [-0.8770748 , -0.62882776, -0.91098301, ..., -1.15746302,
        -0.78941678, -0.7003578 ],
       [ 0.22762249,  0.69186598,  0.21408142, ...,  0.25520295,
         0.47308374,  0.48912879]])

In [584]:
y_train

array([[1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [585]:
y_test

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
    

#converting data into tensor array

In [586]:
x_train_tensor=torch.from_numpy(x_train.astype(np.float32))
x_test_tensor=torch.from_numpy(x_test.astype(np.float32))
y_train_tensor=torch.from_numpy(y_train.astype(np.float32))
y_test_tensor=torch.from_numpy(y_test.astype(np.float32))

In [587]:
x_test_tensor.dtype

torch.float32

In [588]:
class mymodel(nn.Module):
    def __init__(self,new_features):
        super().__init__()
        self.linear1=nn.Linear(new_features,3)
        self.relu=nn.ReLU()
        self.linear2=nn.Linear(3,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self,features):
        out=self.linear1(features)
        out=self.relu(out)
        out=self.linear2(out)
        out=self.sigmoid(out)
        return out

In [589]:
x_train_tensor.shape

torch.Size([455, 30])

In [590]:
s1=y_train_tensor.view(1,-1)

In [591]:
s1.shape

torch.Size([1, 455])

In [592]:
s2=y_train_tensor.view(-1,1)

In [593]:
s2.shape

torch.Size([455, 1])

In [594]:
learning_rate=0.1

In [595]:
epochs=35

In [596]:
x_train.shape[1]

30

In [597]:
object=mymodel(x_train.shape[1])

In [598]:
loss_function=nn.BCELoss()

In [651]:
optimizer=torch.optim.SGD(object.parameters(),lr=learning_rate)

In [600]:
for epoch in range(epochs):

    #forward pass
    y_pred=object(x_train_tensor)
    
    #loss calculation
    loss=loss_function(y_pred,y_train_tensor.view(-1,1))

    #clean gradients or reset process
    optimizer.zero_grad()
    
    #backward propagation
    loss.backward()
    
    #update step
    optimizer.step()

    print(f" {epoch+1},loss:{loss.item()}")


 1,loss:0.6735861897468567
 2,loss:0.6434317827224731
 3,loss:0.6180444359779358
 4,loss:0.5956094264984131
 5,loss:0.5759220123291016
 6,loss:0.5576412081718445
 7,loss:0.5401744246482849
 8,loss:0.5237489342689514
 9,loss:0.5078815817832947
 10,loss:0.4921848773956299
 11,loss:0.47691094875335693
 12,loss:0.462058424949646
 13,loss:0.44757434725761414
 14,loss:0.43354079127311707
 15,loss:0.4199296832084656
 16,loss:0.40663743019104004
 17,loss:0.393907755613327
 18,loss:0.3817327916622162
 19,loss:0.3699793517589569
 20,loss:0.3586239516735077
 21,loss:0.3478708267211914
 22,loss:0.33767056465148926
 23,loss:0.32792219519615173
 24,loss:0.31867045164108276
 25,loss:0.3098921477794647
 26,loss:0.3016022741794586
 27,loss:0.29376521706581116
 28,loss:0.28631865978240967
 29,loss:0.2792689800262451
 30,loss:0.27254149317741394
 31,loss:0.2661373019218445
 32,loss:0.26005974411964417
 33,loss:0.25431838631629944
 34,loss:0.2488728016614914
 35,loss:0.24368558824062347


In [601]:
from torchinfo import summary

In [602]:
x_train_tensor.shape

torch.Size([455, 30])

In [603]:
summary(object,input_size=(455,30))

Layer (type:depth-idx)                   Output Shape              Param #
mymodel                                  [455, 1]                  --
├─Linear: 1-1                            [455, 3]                  93
├─ReLU: 1-2                              [455, 3]                  --
├─Linear: 1-3                            [455, 1]                  4
├─Sigmoid: 1-4                           [455, 1]                  --
Total params: 97
Trainable params: 97
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.04
Input size (MB): 0.05
Forward/backward pass size (MB): 0.01
Params size (MB): 0.00
Estimated Total Size (MB): 0.07

In [604]:
pred1=object(x_test_tensor[0])

In [605]:
(pred1>0.5).float()

tensor([1.])

In [606]:
y_test_tensor[1]

tensor([1.])

In [607]:
actual=y_test_tensor[1]

In [610]:
(pred1==actual).float().mean()

tensor(0.)

In [609]:
with torch.no_grad():
    y_pred=object(x_test_tensor)
    y_pred=(y_pred>0.5).float()
    accuracy=(y_pred==y_test_tensor).float().mean()
    print(f"the accuracy is : {accuracy.item()}")

the accuracy is : 0.9385964870452881


In [611]:
#Dataset    ==> for initialization only

#DataLoader ==> for sending data batchs

#creation of dummy datasets

In [613]:
from sklearn.datasets import make_classification
import torch

In [636]:
x,y=make_classification(
                        n_samples=20,   # no of datas or samples
                        n_features=3,   # no of  columns
                        n_informative=2,#no of informatives
                        n_redundant=0,   #no reduntant in the datas
                        n_classes=2,    #no classes in your label
                        random_state=20 #for reproducability
                        )

In [637]:
x

array([[-1.92340582,  0.36302116,  0.52772847],
       [ 0.35570789,  0.1384218 , -0.96221598],
       [ 0.52777027,  0.42108815, -0.48245091],
       [-1.57257964,  0.26749034,  0.15583822],
       [ 1.34977647, -1.01834071,  0.09878861],
       [-1.44465381, -0.35674894, -1.48238505],
       [-0.1277233 ,  1.26247643,  1.3014294 ],
       [-0.8463147 , -1.46683756, -0.85616422],
       [ 0.73268863, -0.98972705, -1.48571961],
       [-1.10201218,  1.10557442,  0.1140476 ],
       [-0.33223102, -1.6432131 , -0.21966112],
       [ 1.41891414, -1.13599391,  2.09466534],
       [ 0.32626954,  1.47708907, -0.51314511],
       [ 0.53801084,  1.55376789, -0.22832103],
       [ 0.93928588, -1.07485961,  0.69100212],
       [ 1.85971768,  0.63245719, -0.85477549],
       [-0.48171213, -1.41999374, -0.82869277],
       [-0.18163665,  1.71401726, -0.99480191],
       [-1.86506731, -0.81756028,  1.50339816],
       [ 1.17027916, -0.63548335,  0.35942899]])

In [638]:
y

array([1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0])

In [639]:
x=torch.tensor(x,dtype=torch.float32)
y=torch.tensor(y,dtype=torch.float32)

In [640]:
x.dtype

torch.float32

In [641]:
y.dtype

torch.float32

#Example of Dataset

In [642]:
from torch.utils.data import DataLoader,Dataset

In [643]:
class mass(Dataset):
    def __init__(self,features,labels):
        self.features=features
        self.labels=labels
        
    #dunder methods or special methods in python 
    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self, index):
        return self.features[index],self.labels[index]

In [644]:
mas=mass(x,y)

In [645]:
len(mas)

20

In [646]:
mas[2]

(tensor([ 0.5278,  0.4211, -0.4825]), tensor(1.))

#Example of DataLoader

In [647]:
dataloader=DataLoader(mas,batch_size=2,shuffle=False)

In [648]:
print(dataloader)

In [650]:
for batch_data,batch_labels in dataloader:
    print(f"{batch_data}")
    print(f" {batch_labels}")
    print("-"*50)


tensor([[-1.9234,  0.3630,  0.5277],
        [ 0.3557,  0.1384, -0.9622]])
 tensor([1., 1.])
--------------------------------------------------
tensor([[ 0.5278,  0.4211, -0.4825],
        [-1.5726,  0.2675,  0.1558]])
 tensor([1., 1.])
--------------------------------------------------
tensor([[ 1.3498, -1.0183,  0.0988],
        [-1.4447, -0.3567, -1.4824]])
 tensor([0., 0.])
--------------------------------------------------
tensor([[-0.1277,  1.2625,  1.3014],
        [-0.8463, -1.4668, -0.8562]])
 tensor([1., 0.])
--------------------------------------------------
tensor([[ 0.7327, -0.9897, -1.4857],
        [-1.1020,  1.1056,  0.1140]])
 tensor([0., 1.])
--------------------------------------------------
tensor([[-0.3322, -1.6432, -0.2197],
        [ 1.4189, -1.1360,  2.0947]])
 tensor([0., 0.])
--------------------------------------------------
tensor([[ 0.3263,  1.4771, -0.5131],
        [ 0.5380,  1.5538, -0.2283]])
 tensor([1., 1.])
-------------------------------------------