#pytorch basics

#whatever operation we have been perform in the numpy library

#the same opertion we can able to perform in the torch

In [9]:
import torch

In [2]:
print(torch.__version__)

2.5.1+cpu


In [5]:
if torch.cuda.is_available():
    print('cuda')
    print(torch.cuda.get_device_name(0))

In [7]:
a=torch.empty(2,3)

In [8]:
print(a)

tensor([[1.7357e-18, 8.5339e-43, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [10]:
type(a)

torch.Tensor

In [14]:
a.fill_(2)

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [22]:
torch.zero_(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [19]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [24]:
torch.ones_like(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [25]:
torch.rand(2,2)

tensor([[0.6311, 0.1257],
        [0.2527, 0.0204]])

In [30]:
torch.rand(2,2)#it can change the matrix value when you

tensor([[0.7312, 0.7224],
        [0.1992, 0.6948]])

In [27]:
torch.manual_seed(12)
torch.rand(2,2)

tensor([[0.4657, 0.2328],
        [0.4527, 0.5871]])

#manaul_seed can maintain the same state

In [28]:
torch.manual_seed(12)
torch.rand(2,2)

tensor([[0.4657, 0.2328],
        [0.4527, 0.5871]])

In [31]:
two=torch.tensor([[1,2,3],[4,5,6]])
print(two)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [38]:
#syntax for arange(start,stop,step) last value will be excluded
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

In [42]:
torch.linspace(0,1,10) #it sets a boundary between 0 and 1 it create 10 values

tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])

In [44]:
torch.eye(5,5)# used create identical matrix

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [47]:
torch.full((2,2),5)

tensor([[5, 5],
        [5, 5]])

In [48]:
x=torch.tensor([[1,2,3],[3,4,5],[6,7,8]])

In [49]:
print(x)

tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])


In [50]:
print(x.shape)

torch.Size([3, 3])


In [51]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [52]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [55]:
torch.zeros(5)

tensor([0., 0., 0., 0., 0.])

In [57]:
torch.zero_(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [62]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.0554, 0.1573, 0.8137],
        [0.7216, 0.2717, 0.3003],
        [0.6099, 0.5784, 0.6083]])

In [64]:
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [66]:
x=x+2

In [67]:
x*2

tensor([[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]])

In [68]:
x/2

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [69]:
c=torch.tensor([-1,2,-3,4])

In [71]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [72]:
torch.neg(c)

tensor([ 1, -2,  3, -4])

In [73]:
d=torch.tensor([1.9,2.4,4.8,3.5])

In [74]:
torch.round(d)

tensor([2., 2., 5., 4.])

In [75]:
torch.floor(d)

tensor([1., 2., 4., 3.])

In [76]:
torch.ceil(d)

tensor([2., 3., 5., 4.])

In [77]:
c=torch.randint(size=(2,3),low=0,high=10)

In [78]:
c

tensor([[9, 5, 2],
        [9, 7, 0]])

In [79]:
torch.sum(c)

tensor(32)

In [82]:
torch.sum(c,dim=0)#0 means columns wise vertically it can sum it

tensor([18, 12,  2])

In [83]:
torch.sum(c,dim=1)#1 means row wise vertically it can sum it

tensor([16, 16])

In [92]:
torch.tensor(c,dtype=torch.float32)#change the datatype to float and printing the value 

C:\Users\user\AppData\Local\Temp\ipykernel_15324\2399469833.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.tensor(c,dtype=torch.float32)#change the datatype to float and printing the value


tensor([[9., 5., 2.],
        [9., 7., 0.]])

In [87]:
torch.mean(c,dim=1,dtype=torch.float32)

tensor([5.3333, 5.3333])

In [93]:
torch.max(c)

tensor(9)

In [94]:
torch.min(c)

tensor(0)

In [97]:
c

tensor([[9, 5, 2],
        [9, 7, 0]])

In [98]:
#argmax return the index of highest value in the given matix
torch.argmax(c)

tensor(0)

In [99]:
#argmin return the index of lowest value in the given matix
torch.argmin(c)

tensor(5)

In [102]:
f=torch.randint(size=(2,3),low=0,high=10)
print(f)

tensor([[3, 1, 3],
        [7, 0, 6]])


In [103]:
g=torch.randint(size=(3,2),low=0,high=10)
print(g)

tensor([[8, 2],
        [3, 3],
        [5, 9]])


In [104]:
c=torch.matmul(f,g)

In [105]:
c

tensor([[42, 36],
        [86, 68]])

In [108]:
a=torch.tensor([1,2])

In [109]:
b=torch.tensor([3,4])

In [111]:
torch.dot(a,b)

tensor(11)

In [112]:
g

tensor([[8, 2],
        [3, 3],
        [5, 9]])

In [113]:
torch.transpose(g,0,1)

tensor([[8, 3, 5],
        [2, 3, 9]])

In [120]:
c=torch.tensor([[1,2],[4,5]],dtype=torch.float32)

In [121]:
torch.inverse(c)

tensor([[-1.6667,  0.6667],
        [ 1.3333, -0.3333]])

In [122]:
torch.log(c)

tensor([[0.0000, 0.6931],
        [1.3863, 1.6094]])

In [123]:
torch.exp(c)

tensor([[  2.7183,   7.3891],
        [ 54.5981, 148.4132]])

In [125]:
torch.softmax(c,0)

tensor([[0.0474, 0.0474],
        [0.9526, 0.9526]])

In [126]:
torch.softmax(c,1)

tensor([[0.2689, 0.7311],
        [0.2689, 0.7311]])