training the dummy data using dataloader with batch size

In [1]:
from sklearn.datasets import make_classification
import torch

In [2]:
x,y=make_classification(
    n_samples=20,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_repeated=0,
    n_classes=2,
    random_state=4

)

In [3]:
x

array([[ 2.78339941, -1.5077206 ],
       [ 1.53760952, -1.20485962],
       [-0.54042266,  0.93028596],
       [ 0.65388863,  0.0791946 ],
       [-1.10808987,  0.26451644],
       [ 2.66630946, -1.36632771],
       [ 2.61756228,  1.74756539],
       [-0.48623435,  0.82526196],
       [-0.42490177,  0.88673622],
       [-0.36426545,  0.89368899],
       [ 2.74542676, -1.48269336],
       [ 0.58188765,  2.99345889],
       [ 0.39650799, -0.49423453],
       [-1.73619444,  1.09931611],
       [-0.98829543, -1.34872568],
       [-0.90353091, -0.47626093],
       [ 0.18605101, -0.80503454],
       [ 0.96160806,  0.13892933],
       [-1.27704863, -0.82592822],
       [-1.18083407, -0.98045609]])

In [4]:
y

array([0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0])

In [5]:
x=torch.tensor(x,dtype=torch.float32)
y=torch.tensor(y,dtype=torch.float32)

In [6]:
x

tensor([[ 2.7834, -1.5077],
        [ 1.5376, -1.2049],
        [-0.5404,  0.9303],
        [ 0.6539,  0.0792],
        [-1.1081,  0.2645],
        [ 2.6663, -1.3663],
        [ 2.6176,  1.7476],
        [-0.4862,  0.8253],
        [-0.4249,  0.8867],
        [-0.3643,  0.8937],
        [ 2.7454, -1.4827],
        [ 0.5819,  2.9935],
        [ 0.3965, -0.4942],
        [-1.7362,  1.0993],
        [-0.9883, -1.3487],
        [-0.9035, -0.4763],
        [ 0.1861, -0.8050],
        [ 0.9616,  0.1389],
        [-1.2770, -0.8259],
        [-1.1808, -0.9805]])

In [7]:
y

tensor([0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 0., 1.,
        0., 0.])

In [8]:
import torch.nn as nn

In [9]:
class mymodel(nn.Module):
    def __init__(self,new_features,hidden_layer):
        super().__init__()
        self.linear1=nn.Linear(new_features,hidden_layer)
        self.relu=nn.ReLU()
        self.linear2=nn.Linear(hidden_layer,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self,features):
        out=self.linear1(features)
        out=self.relu(out)
        out=self.linear2(out)
        out=self.sigmoid(out)
        return out

In [10]:
x.shape[1]

2

In [11]:
model=mymodel(x.shape[1],3)

In [12]:
from torch.utils.data import DataLoader,Dataset

In [13]:
class SimpleNN(Dataset):
    def __init__(self,feature,label):
        self.feature=feature
        self.label=label

    def __len__(self):
        return self.feature.shape[0]
    
    def __getitem__(self, index):
        return self.feature[index],self.label[index]
    

In [14]:
x_dataset=SimpleNN(x,y)

In [15]:
len(x)

20

In [16]:
x_dataset[2]

(tensor([-0.5404,  0.9303]), tensor(1.))

In [17]:
import os
os.cpu_count()

8

In [18]:
loader=DataLoader(
    dataset=x_dataset,
    batch_size=2,
    shuffle=True)

In [19]:
loader

In [20]:
import torch.optim as optim

In [21]:
learning_rate=0.01

In [22]:
epochs=30

In [23]:
loss_function=nn.BCELoss()

In [24]:
optimizer=optim.Adam(model.parameters(),lr=learning_rate)

In [25]:
for epoch in range(epochs):
    for batch_data,batch_label in loader:
        input=batch_data
        output=batch_label
        print(input)
        print(output)
        y_pred=model(input)

        loss=loss_function(y_pred,output.view(-1,1))

        optimizer.zero_grad()

        loss.backward()

        optimizer.step()

    print(f" the number of epochs {epoch+1} and loss is {loss}")

tensor([[-0.3643,  0.8937],
        [-0.9035, -0.4763]])
tensor([1., 0.])
tensor([[ 0.5819,  2.9935],
        [ 0.3965, -0.4942]])
tensor([1., 1.])
tensor([[ 0.6539,  0.0792],
        [-1.1081,  0.2645]])
tensor([1., 0.])
tensor([[-0.4862,  0.8253],
        [ 0.1861, -0.8050]])
tensor([1., 0.])
tensor([[-0.4249,  0.8867],
        [ 2.6176,  1.7476]])
tensor([1., 1.])
tensor([[ 2.7834, -1.5077],
        [ 0.9616,  0.1389]])
tensor([0., 1.])
tensor([[-0.5404,  0.9303],
        [ 2.7454, -1.4827]])
tensor([1., 0.])
tensor([[-1.1808, -0.9805],
        [-1.2770, -0.8259]])
tensor([0., 0.])
tensor([[ 1.5376, -1.2049],
        [ 2.6663, -1.3663]])
tensor([0., 0.])
tensor([[-1.7362,  1.0993],
        [-0.9883, -1.3487]])
tensor([1., 0.])
 the number of epochs 1 and loss is 0.7718877792358398
tensor([[-0.5404,  0.9303],
        [ 0.3965, -0.4942]])
tensor([1., 1.])
tensor([[-0.4249,  0.8867],
        [ 0.1861, -0.8050]])
tensor([1., 0.])
tensor([[ 1.5376, -1.2049],
        [ 2.7454, -1.4827]])


In [26]:
model.linear1.weight

Parameter containing:
tensor([[ 0.1549,  0.6920],
        [-1.4237, -1.0511],
        [ 0.3351,  1.5448]], requires_grad=True)

In [27]:
model.linear2.weight

Parameter containing:
tensor([[ 0.3250, -1.3835,  1.6528]], requires_grad=True)

In [28]:
model.linear1.bias

Parameter containing:
tensor([0.5240, 0.1954, 1.1085], requires_grad=True)

In [29]:
model.linear2.bias

Parameter containing:
tensor([-0.5363], requires_grad=True)

In [30]:
from torchinfo import summary

In [31]:
summary(model)

Layer (type:depth-idx)                   Param #
mymodel                                  --
├─Linear: 1-1                            9
├─ReLU: 1-2                              --
├─Linear: 1-3                            4
├─Sigmoid: 1-4                           --
Total params: 13
Trainable params: 13
Non-trainable params: 0